parameters:
- name: name
  type: string
  default: null
- name: pool
  type: object
  default: {}
- name: publishConfig
  type: object
  default: null
# Custom steps to set up ImageBuilder instead of pulling from MCR (e.g., bootstrap from source).
# Runs before ImageBuilder pull. If non-empty, skips the default ImageBuilder pull.
- name: customInitSteps
  type: stepList
  default: []
# Custom steps that run after ImageBuilder is set up but before copy-base-images runs.
- name: customCopyBaseImagesInitSteps
  type: stepList
  default: []
- name: additionalOptions
  type: string
  default: ''
- name: continueOnError
  type: string
  default: false
- name: versionsRepoRef
  type: string
  default: ""

jobs:
- template: /eng/docker-tools/templates/jobs/copy-base-images.yml@self
  parameters:
    name: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    publishConfig: ${{ parameters.publishConfig }}
    customInitSteps: ${{ parameters.customInitSteps }}
    customCopyBaseImagesInitSteps: ${{ parameters.customCopyBaseImagesInitSteps }}
    additionalOptions: ${{ parameters.additionalOptions }}
    acr: ${{ parameters.publishConfig.InternalMirrorRegistry }}
    versionsRepoRef: ${{ parameters.versionsRepoRef }}
