parameters:
  name: null
  pool: {}
  matrix: {}
  testJobTimeout: 60
  preBuildValidation: false
  internalProjectName: null
  publishConfig: null
  customInitSteps: []
  sourceBuildPipelineRunId: ""

jobs:
- job: ${{ parameters.name }}
  ${{ if eq(parameters.preBuildValidation, 'false') }}:
    condition: and(succeeded(), ${{ parameters.matrix }})
    dependsOn: GenerateTestMatrix
    strategy:
      matrix: $[ ${{ parameters.matrix }} ]
  ${{ if eq(parameters.preBuildValidation, 'true') }}:
    condition: and(succeeded(), ne(variables.testScriptPath, ''))
  pool: ${{ parameters.pool }}
  timeoutInMinutes: ${{ parameters.testJobTimeout }}
  steps:
  - template: /eng/docker-tools/templates/steps/test-images-linux-client.yml@self
    parameters:
      preBuildValidation: ${{ parameters.preBuildValidation }}
      internalProjectName: ${{ parameters.internalProjectName }}
      publishConfig: ${{ parameters.publishConfig }}
      customInitSteps: ${{ parameters.customInitSteps }}
      sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
