apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dotnet
  labels:
    app: aspnetapp
spec:
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: dotnetnonroot.azurecr.io/aspnetapp
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 64198
---
apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet
spec:
  type: NodePort
  selector:
    app: aspnetapp
  ports:
    - port: 8080
