parameters:
  isPullRequestPipeline: false
  noCache: false
  internalProjectName: null
  publicProjectName: null

stages:
- template: ../../common/templates/stages/build-test-publish-repo.yml
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    internalVersionsRepoRef: InternalVersionsRepo
    publicVersionsRepoRef: PublicVersionsRepo
    ${{ if parameters.isPullRequestPipeline }}:
      buildMatrixType: platformVersionedOs
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build --custom-build-leg-group test-dependencies
    ${{ if not(parameters.isPullRequestPipeline) }}:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies
    ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
      customPublishVariables:
      - group: DotNet-AllOrgs-Darc-Pats

    # Template paths must be relative to the YAML job that executes them
    customBuildInitSteps:
    - template: ../../../pipelines/steps/set-public-source-branch-var.yml
    customPublishInitSteps:
    - template: ../../../pipelines/steps/set-public-source-branch-var.yml
    - template: ../../../pipelines/steps/set-publish-mcrdocs-args-var.yml
    
