# A simple wrapper around the build-and-test and publish templates so that both
# templates can easily be called at the same time with the same parameters.

# Any repo-specific overrides should be added in the individual build/publish
# templates themselves, not in this file.

parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null
  linuxAmd64Pool: ""
  isInternalServicingValidation: false
  sourceBuildPipelineRunId: ""

stages:
- template: /eng/pipelines/stages/build-and-test.yml@self
  parameters:
    ${{ insert }}: ${{ parameters }}
- template: /eng/pipelines/stages/publish.yml@self
  parameters:
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
