# A wrapper template around the common .NET build-test-publish-repo template with settings
# specific to the Dockerfiles in this repo.

parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null

stages:
- template: ../../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    ${{ if eq(variables['System.TeamProject'], parameters.publicProjectName) }}:
      buildMatrixType: platformVersionedOs
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build --custom-build-leg-group test-dependencies
    ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies
    testMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies

    # Template paths must be relative to the YAML job that executes them
    customBuildInitSteps:
    - template: ../../../pipelines/steps/set-imagebuilder-build-args-var.yml
    - template: ../../../pipelines/steps/set-public-source-branch-var.yml
    - powershell: |
        $imageBuilderBuildArgs = "$(imageBuilderBuildArgs)"
        if ("$(publishRepoPrefix)".Contains("/internal/")) {
          if ("$env:ENABLEINTERNAL3_1" -eq "true") {
            $sasQueryString = "$(dotnetclimsrc-read-sas-token)"
          }
          else {
            $sasQueryString = "$(dotnetbuilds-internal-container-read-token)"
          }
          
          $imageBuilderBuildArgs += " --build-arg SAS_QUERY_STRING='$sasQueryString'"
        }
        echo "##vso[task.setvariable variable=imageBuilderBuildArgs]$imageBuilderBuildArgs"
      displayName: Set Custom Build Variables
    - powershell: |
        # Forward team project name for consumption by test script
        $testRunnerOptions="-e SYSTEM_TEAMPROJECT='$env:SYSTEM_TEAMPROJECT'"

        echo "##vso[task.setvariable variable=testRunner.options]$testRunnerOptions"
      displayName: Set Custom Test Variables
    customTestInitSteps:
    - powershell: |
        # Forward team project name for consumption by test script
        $testRunnerOptions="-e SYSTEM_TEAMPROJECT='$env:SYSTEM_TEAMPROJECT'"
        $testInit=""

        if ("$(publishRepoPrefix)".Contains("/internal/")) {
          if ("$env:ENABLEINTERNAL3_1" -eq "true") {
            $sasQueryString = "$(dotnetclimsrc-read-sas-token)"
          }
          else {
            $sasQueryString = "$(dotnetbuilds-internal-container-read-token)"
          }

          if ($Env:AGENT_OS -eq 'Linux') {
            $testRunnerOptions="$testRunnerOptions -e SAS_QUERY_STRING='$sasQueryString' -e NUGET_FEED_PASSWORD='$(dn-bot-dnceng-artifact-feeds-rw)'"
          }

          if ($Env:AGENT_OS -eq 'Windows_NT') {
              # Be sure to use a verbatim string when referencing the environment variables. We don't want the
              # variables to be resolved in this script. We're generating the script here to be executed by the
              # test step.
              $testInit='$Env:SAS_QUERY_STRING=' + "'$sasQueryString'" + '; $Env:NUGET_FEED_PASSWORD=''$(dn-bot-dnceng-artifact-feeds-rw)'''
          }
        }
        
        echo "##vso[task.setvariable variable=testRunner.options]$testRunnerOptions"
        echo "##vso[task.setvariable variable=test.init]$testInit"
      displayName: Set Custom Test Variables
    customPublishInitSteps:
    - template: ../../../pipelines/steps/set-public-source-branch-var.yml
    - template: ../../../pipelines/steps/set-publish-mcrdocs-args-var.yml
