# A wrapper template around the common .NET build-test-publish-repo template with settings
# specific to the Dockerfiles in this repo.

parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null
  linuxAmd64Pool: ""
  isInternalServicingValidation: false

stages:
- template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}
    ${{ if or(eq(variables['System.TeamProject'], parameters.publicProjectName), and(eq(variables['System.TeamProject'], parameters.internalProjectName), or(eq(variables['Build.Reason'], 'PullRequest'), eq(parameters.isInternalServicingValidation, 'true')))) }}:
      buildMatrixType: platformVersionedOs
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build --custom-build-leg-group test-dependencies
    ${{ elseif eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies
    testMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies

    # Template paths must be relative to the YAML job that executes them
    customBuildInitSteps:
    - template: /eng/pipelines/steps/set-public-source-branch-var.yml@self
    - powershell: |
        $imageBuilderBuildArgs = "$IMAGEBUILDERBUILDARGS"
        if ("${{ parameters.IsInternalServicingValidation }}" -eq "true") {
          $accessToken = "$(System.AccessToken)"
          $imageBuilderBuildArgs += " --build-arg ACCESSTOKEN='$accessToken'"
        }
        echo "##vso[task.setvariable variable=imageBuilderBuildArgs]$imageBuilderBuildArgs"
      displayName: Set Custom Build Variables
    - template: /eng/pipelines/steps/set-custom-test-variables.yml@self
    customTestInitSteps:
    - template: /eng/pipelines/steps/set-custom-test-variables.yml@self
    customPublishInitSteps:
    - template: /eng/pipelines/steps/set-public-source-branch-var.yml@self
    - template: /eng/pipelines/steps/set-publish-mcrdocs-args-var.yml@self
