# A wrapper template around the common .NET publish template with settings
# specific to the Dockerfiles in this repo.

parameters:
  - name: internalProjectName
    type: string
    default: null
  - name: publicProjectName
    type: string
    default: null
  - name: linuxAmd64Pool
    type: string
    default: ""
  - name: isInternalServicingValidation
    type: boolean
    default: false
  - name: isStandalonePublish
    type: boolean
    default: false
  - name: customPublishInitSteps
    type: stepList
    default: []
  - name: sourceBuildPipelineDefinitionId
    type: string
    default: ''
  - name: sourceBuildPipelineRunId
    type: string
    default: ''
  - name: versionsRepoRef
    type: string
    default: ''
  - name: overrideImageInfoCommit
    type: boolean
    default: false

stages:
- template: /eng/common/templates/stages/dotnet/publish.yml@self
  parameters:
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    versionsRepoRef: ${{ parameters.versionsRepoRef }}
    isInternalServicingValidation: ${{ parameters.isInternalServicingValidation }}
    isStandalonePublish: ${{ parameters.isStandalonePublish }}
    pool: ${{ parameters.linuxAmd64Pool }}
    customPublishInitSteps:
    - ${{ parameters.customPublishInitSteps }}
    - template: /eng/pipelines/steps/set-public-source-branch-var.yml@self
    - template: /eng/pipelines/steps/set-publish-mcrdocs-args-var.yml@self
    sourceBuildPipelineDefinitionId: ${{ parameters.sourceBuildPipelineDefinitionId }}
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
    overrideImageInfoCommit: ${{ parameters.overrideImageInfoCommit }}
