# A wrapper template around the common .NET publish template with settings
# specific to the Dockerfiles in this repo.

parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null
  linuxAmd64Pool: ""
  isInternalServicingValidation: false
  sourceBuildPipelineRunId: ""

stages:
- template: /eng/common/templates/stages/dotnet/publish.yml@self
  parameters:
    ${{ insert }}: ${{ parameters }}
    customPublishInitSteps:
    - template: /eng/pipelines/steps/set-public-source-branch-var.yml@self
    - template: /eng/pipelines/steps/set-publish-mcrdocs-args-var.yml@self
