# syntax=docker/dockerfile:1
# Learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md
FROM mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim-amd64 AS build
ARG TARGETARCH
RUN dpkg --add-architecture arm64 \
    && apt-get update \
    && apt-get install -y \
        clang \
        gcc-aarch64-linux-gnu \
        llvm \
        zlib1g-dev \
        zlib1g-dev:arm64 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /source

# Copy project file and restore as distinct layers
COPY --link *.csproj NuGet.config .
RUN dotnet restore -r linux-$TARGETARCH

# Copy source code and publish app
COPY --link . .
RUN dotnet publish -a $TARGETARCH --sc --no-restore -o /app releasesapi.csproj
RUN rm /app/*.dbg /app/*.Development.json


# Final stage/image
FROM mcr.microsoft.com/dotnet/runtime-deps:9.0
WORKDIR /app
COPY --link --from=build /app .
USER $APP_UID
ENTRYPOINT ["./releasesapi"]
