#!/bin/bash

set -e

echo "Pushing additional sdk tags"
imageName=$DOCKER_REPO":2.0.0-preview1-sdk"
docker tag $IMAGE_NAME $imageName
docker push $imageName

imageName=$DOCKER_REPO":2-sdk"
docker tag $IMAGE_NAME $imageName
docker push $imageName
