jobs:
  ################################################################################
  # Initialization - Generate the VSTS build matrix
  ################################################################################
  - job: GenerateMatrices
    pool:
      name: DotNet-Build
      demands: agent.os -equals linux
    workspace:
      clean: all
    steps:
      - template: ../steps/init-docker-linux.yml
      - script: $(runImageBuilderCmd) generateBuildMatrix --manifest $(manifest) --type build
        name: buildMatrix
      - script: $(runImageBuilderCmd) generateBuildMatrix --manifest $(manifest) --type test
        name: testMatrix
      - template: ../steps/cleanup-docker-linux.yml

  ################################################################################
  # Build Images
  ################################################################################
  - template: build-images-linux-client.yml
    parameters:
      name: Build_Linux_amd64
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixLinuxAmd64'] ]
  - template: build-images-linux-client.yml
    parameters:
      name: Build_Linux_arm32v7
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixLinuxArm32v7'] ]
      useRemoteDockerServer: true
      dockerServerDemands:
        - RemoteDockerServerOS -equals linux
        - RemoteDockerServerArch -equals arm32v7
  - template: build-images-windows-client.yml
    parameters:
      name: Build_NanoServerSac2016_amd64
      osVersion: nanoserver-sac2016
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixNanoserverSac2016Amd64'] ]
  - template: build-images-windows-client.yml
    parameters:
      name: Build_NanoServer1709_amd64
      osVersion: nanoserver-1709
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS3
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixNanoserver1709Amd64'] ]
  - template: build-images-windows-client.yml
    parameters:
      name: Build_NanoServer1803_amd64
      osVersion: nanoserver-1803
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS4
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixNanoserver1803Amd64'] ]

  ################################################################################
  # Test Images
  ################################################################################
  - template: test-images-linux-client.yml
    parameters:
      name: Test_Linux_amd64
      buildDependencies: Build_Linux_amd64
      matrix: $[ dependencies.GenerateMatrices.outputs['testMatrix.testMatrixLinuxAmd64'] ]
      architecture: amd64
  - template: test-images-linux-client.yml
    parameters:
      name: Test_Linux_arm32v7
      buildDependencies: Build_Linux_arm32v7
      matrix: $[ dependencies.GenerateMatrices.outputs['testMatrix.testMatrixLinuxArm32v7'] ]
      useRemoteDockerServer: true
      dockerServerDemands:
        - RemoteDockerServerOS -equals linux
        - RemoteDockerServerArch -equals arm32v7
      architecture: arm
  - template: test-images-windows-client.yml
    parameters:
      name: Test_NanoServerSac2016_amd64
      buildDependencies: Build_NanoServerSac2016_amd64
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
      matrix: $[ dependencies.GenerateMatrices.outputs['testMatrix.testMatrixNanoserverSac2016Amd64'] ]
  - template: test-images-windows-client.yml
    parameters:
      name: Test_NanoServer1709_amd64
      buildDependencies: Build_NanoServer1709_amd64
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS3
      matrix: $[ dependencies.GenerateMatrices.outputs['testMatrix.testMatrixNanoserver1709Amd64'] ]
  - template: test-images-windows-client.yml
    parameters:
      name: Test_NanoServer1803_amd64
      buildDependencies: Build_NanoServer1803_amd64
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS4
      matrix: $[ dependencies.GenerateMatrices.outputs['testMatrix.testMatrixNanoserver1803Amd64'] ]

  ################################################################################
  # Publish Images
  ################################################################################
  - template: copy-images-linux.yml
    parameters:
      name: Copy_Images_Linux_amd64
      architecture: amd64
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixLinuxAmd64'] ]
  - template: copy-images-linux.yml
    parameters:
      name: Copy_Images_Linux_arm32v7
      architecture: arm
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixLinuxArm32v7'] ]
  - template: copy-images-windows.yml
    parameters:
      name: Copy_Images_NanoServerSac2016_amd64
      osVersion: nanoserver-sac2016
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixNanoserverSac2016Amd64'] ]
  - template: copy-images-windows.yml
    parameters:
      name: Copy_Images_NanoServer1709_amd64
      osVersion: nanoserver-1709
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS3
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixNanoserver1709Amd64'] ]
  - template: copy-images-windows.yml
    parameters:
      name: Copy_Images_NanoServer1803_amd64
      osVersion: nanoserver-1803
      demands: VSTS_OS -equals Windows_Server_2016_Data_Center_RS4
      matrix: $[ dependencies.GenerateMatrices.outputs['buildMatrix.buildMatrixNanoserver1803Amd64'] ]

  - template: publish-finalize.yml
