parameters:
  name: null
  osVersion: null
  demands: []
  matrix: {}
jobs:
  - job: ${{ parameters.name }}
    condition: or(and(succeeded(), eq(variables['singlePhase'], '')), eq(variables['singlePhase'], 'build'))
    dependsOn: GenerateMatrices
    pool:
      name: DotNetCore-Infra
      demands: ${{ parameters.demands }}
    strategy:
      matrix: ${{ parameters.matrix }}
    workspace:
      clean: all
    variables:
      osVersion: ${{ parameters.osVersion }}
    steps:
      - template: ../steps/init-docker-windows.yml
      - script: $(runImageBuilderCmd) build --manifest $(manifest) --os-version $(osVersion) --skip-test $(imageBuilderPaths) --repo-override microsoft/$(repo)=$(acr.server)/$(repo)-$(stagingRepo.suffix) --push --server $(acr.server) --username $(acr.userName) --password $(BotAccount-dotnet-docker-acr-bot-password) $(imageBuilder.queueArgs)
        displayName: Build Images
      - template: ../steps/cleanup-docker-windows.yml
