parameters:
  pool: {}
  matrix: {}
jobs:
- job: Copy_Images
  condition: and(succeeded(), ${{ parameters.matrix }})
  dependsOn: GeneratePublishMatrix
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  steps:
  - template: ../steps/init-docker-linux.yml
  - script: >
      $(runImageBuilderCmd) copyAcrImages
      --manifest $(manifest)
      $(imageBuilderPaths)
      --os-type $(osType)
      --os-version "$(osVersion)"
      --architecture $(architecture)
      --registry-override $(acr.server)
      --repo-prefix $(publishRepoPrefix)
      $(imageBuilder.queueArgs)
      $(stagingRepoPrefix)
      $(acr.servicePrincipalName)
      $(app-dotnetdockerbuild-client-secret)
      $(acr.servicePrincipalTenant)
      $(acr.subscription)
    displayName: Copy Images
  - template: ../steps/cleanup-docker-linux.yml
