parameters:
  name: null
  osVersion: null
  demands: []
  matrix: {}
jobs:
  - job: ${{ parameters.name }}
    condition: or(eq(variables['singlePhase'], 'publish'), and(eq(variables['singlePhase'], ''), or(succeeded(), and(eq(variables['repo'], 'dotnet-samples'), eq(variables['singlePhase'], ''), succeeded('Build_Linux_amd64'), succeeded('Build_Linux_arm32v7'), succeeded('Build_NanoServerSac2016_amd64'), succeeded('Build_NanoServer1709_amd64'), succeeded('Build_NanoServer1803_amd64')))))
    dependsOn:
      - GenerateMatrices
      - Test_Linux_amd64
      - Test_Linux_arm32v7
      - Test_NanoServerSac2016_amd64
      - Test_NanoServer1709_amd64
      - Test_NanoServer1803_amd64
    pool:
      name: DotNetCore-Infra
      demands: ${{ parameters.demands }}
    strategy:
      matrix: ${{ parameters.matrix }}
    workspace:
      clean: all
    variables:
      osVersion: ${{ parameters.osVersion }}
    steps:
      - template: ../steps/init-docker-windows.yml
      - script: $(runImageBuilderCmd) copyImages --manifest $(manifest) --os-version $(osVersion) $(imageBuilderPaths) --source-server $(acr.server) --source-username $(acr.userName) --source-password $(BotAccount-dotnet-docker-acr-bot-password) --destination-username $(dockerRegistry.userName) --destination-password $(BotAccount-dotnet-dockerhub-bot-password) $(imageBuilder.queueArgs) $(imageBuilder.publishQueueArgs) $(acr.server)/$(repo)-$(stagingRepo.suffix)
        displayName: Copy Images
      - template: ../steps/cleanup-docker-windows.yml
