parameters:
  pool: {}
jobs:
- job: Publish_Finalize
  condition: succeeded('Copy_Images')
  dependsOn:
  - Copy_Images
  pool: ${{ parameters.pool }}
  variables:
    imageBuilder.commonCmdArgs: >
      --manifest $(manifest)
      --registry-override $(acr.server)
      $(imageBuilder.queueArgs)
  steps:
  - template: ../steps/init-docker-linux.yml
  - script: >
      $(runImageBuilderCmd) publishManifest
      --repo-prefix $(publishRepoPrefix)
      --username $(acr.userName)
      --password $(BotAccount-dotnet-docker-acr-bot-password)
      $(imageBuilder.commonCmdArgs)
    displayName: Publish Manifest
  - script: >
      $(runImageBuilderCmd) publishMcrReadmes
      $(dotnetBot-userName)
      $(dotnetBot-email)
      $(dotnet-bot-user-repo-adminrepohook-pat)
      $(imageBuilder.commonCmdArgs)
    displayName: Publish Readme
  - template: ../steps/cleanup-docker-linux.yml
