parameters:
  pool: {}
jobs:
- job: Publish
  pool: ${{ parameters.pool }}
  variables:
    imageBuilder.commonCmdArgs: >
      --manifest $(manifest)
      --registry-override $(acr.server)
      $(imageBuilder.queueArgs)
  steps:
  - template: ../steps/init-docker-linux.yml
  - script: >
      $(runImageBuilderCmd) copyAcrImages
      $(stagingRepoPrefix)
      $(acr.servicePrincipalName)
      $(app-dotnetdockerbuild-client-secret)
      $(acr.servicePrincipalTenant)
      $(acr.subscription)
      $(acr.resourceGroup)
      --os-type '*'
      --architecture '*'
      --repo-prefix $(publishRepoPrefix)
      $(imageBuilder.pathArgs)
      $(imageBuilder.commonCmdArgs)
    displayName: Copy Images
  - script: >
      $(runImageBuilderCmd) publishManifest
      --repo-prefix $(publishRepoPrefix)
      --username $(acr.userName)
      --password $(BotAccount-dotnet-docker-acr-bot-password)
      --os-type '*'
      --architecture '*'
      $(imageBuilder.pathArgs)
      $(imageBuilder.commonCmdArgs)
    displayName: Publish Manifest
  - script: >
      $(runImageBuilderCmd) publishMcrReadmes
      $(dotnetBot-userName)
      $(dotnetBot-email)
      $(dotnet-bot-user-repo-adminrepohook-pat)
      $(imageBuilder.commonCmdArgs)
    displayName: Publish Readme
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: Component Detection
  - template: ../steps/cleanup-docker-linux.yml
