parameters:
  name: null
  buildDependencies: []
  pool: {}
  matrix: {}
  useRemoteDockerServer: false
jobs:
- job: ${{ parameters.name }}
  condition: "
    and(
      not(contains(variables['manifest'], 'samples')),
      ${{ parameters.matrix }},
      or(
        and(
          succeeded(),
          eq(variables['singlePhase'], '')),
        eq(variables['singlePhase'], 'test')))"
  dependsOn:
  - GenerateMatrices
  - ${{ parameters.buildDependencies }}
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  steps:
  - template: ../steps/test-images-linux-client.yml
    parameters:
      useRemoteDockerServer: ${{ parameters.useRemoteDockerServer }}
      setupImageBuilder: false
      setupTestRunner: true
