parameters:
  name: null
  buildDependencies: []
  dependsOn: null
  demands: []
  matrix: {}
jobs:
  - job: ${{ parameters.name }}
    condition: and(ne(variables['repo'], 'dotnet-samples'), or(and(succeeded(), eq(variables['singlePhase'], '')), eq(variables['singlePhase'], 'test')))
    dependsOn:
      - GenerateMatrices
      - ${{ parameters.buildDependencies }}
    pool:
      name: DotNetCore-Infra
      demands: ${{ parameters.demands }}
    strategy:
      matrix: ${{ parameters.matrix }}
    workspace:
      clean: all
    steps:
      - template: ../steps/init-docker-windows.yml
        parameters:
          setupImageBuilder: false
      - script: docker login -u $(acr.userName) -p $(BotAccount-dotnet-docker-acr-bot-password) $(acr.server)
        displayName: Docker login
      - powershell: ./tests/run-tests.ps1 -VersionFilter $(dotnetVersion)* -OSFilter $(osVersion) -Repo $(acr.server)/$(repo)-$(stagingRepo.suffix)
        displayName: Test Images
      - script: docker logout
        displayName: Docker logout
        condition: always()
        continueOnError: true
      - task: PublishTestResults@2
        displayName: Publish Test Results
        condition: always()
        continueOnError: true
        inputs:
          testRunner: vSTest
          testResultsFiles: 'tests/**/*.trx'
          mergeTestResults: true
          publishRunAttachments: true
          testRunTitle: Windows $(dotnetVersion) $(osVersion) amd64
      - template: ../steps/cleanup-docker-windows.yml
