apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dotnet
  labels:
    app: aspnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: dotnetnonroot.azurecr.io/aspnetapp
        resources:
          requests:
            memory: "60Mi"
          limits:
            memory: "100Mi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet
spec:
  type: NodePort
  selector:
    app: aspnetapp
  ports:
    - port: 8080
