{{
    _ ARGS:
        is-zip (optional): If the file to be installed is a zip. Otherwise, assume it is a .tar.gz. ^

    set basePkgs to ["ca-certificates"]^
    set extractionPkgs to when(ARGS["is-zip"], ["unzip"], ["gzip", "tar"]) ^

    _ Arrays in cottle are actually key-value maps. Sorting the array sorts by value
        but does not change the key value. In order to have the right index in the
        array, we must call `cat` again to reset the indices (keys) in the map. ^
    set pkgs to cat(sort(cat(basePkgs, extractionPkgs)))

}}RUN {{InsertTemplate("Dockerfile.linux.install-pkgs", [ "pkgs": pkgs ])}}
