RUN {{InsertTemplate("Dockerfile.linux.install-pkgs",
    [
        "pkgs": when(find(OS_VERSION, "1.0") >= 0,
            [
                "ca-certificates-microsoft"
            ],
            [
                "ca-certificates-microsoft",
                "gzip",
                "tar"
            ])
    ])}}
