#!/bin/bash

set -e

echo "Pushing additional sdk tags"
imageName=$DOCKER_REPO":1.1.1-sdk"
docker tag $IMAGE_NAME $imageName
docker push $imageName

imageName=$DOCKER_REPO":1.1.1-sdk-1.0.0"
docker tag $IMAGE_NAME $imageName
docker push $imageName

imageName=$DOCKER_REPO":1-sdk"
docker tag $IMAGE_NAME $imageName
docker push $imageName

imageName=$DOCKER_REPO":sdk"
docker tag $IMAGE_NAME $imageName
docker push $imageName

imageName=$DOCKER_REPO":latest"
docker tag $IMAGE_NAME $imageName
docker push $imageName
