apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-resource-limits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        resources:
          requests:
            memory: "60Mi"
          limits:
            memory: "100Mi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-resource-limits
spec:
  type: ClusterIP
  selector:
    app: aspnetapp
  ports:
    - port: 80
