apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-resource-limits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "60Mi"
            cpu: "250m" # same as 0.25
          limits:
            memory: "100Mi"
            cpu: "500m" # same as 0.5
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-resource-limits
spec:
  type: ClusterIP
  selector:
    app: aspnetapp
  ports:
  - name: aspnetapp
    protocol: TCP
    port: 8080
    targetPort: 80

