apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: bombardier
        image: dotnetnonroot.azurecr.io/bombardier
        args: ["--duration=20s", "--timeout=1s", "http://aspnetapp.default.svc.cluster.local/Environment"]
      restartPolicy: Never
