# escape=`

ARG REPO=mcr.microsoft.com/dotnet/runtime

# Installer image
FROM mcr.microsoft.com/windows/servercore:{{OS_VERSION_NUMBER}}-amd64 AS installer

# Install ASP.NET Core Runtime
RUN {{InsertTemplate("../Dockerfile.windows.install-aspnet", [], "    ")}}


# ASP.NET Core image
FROM $REPO:{{VARIABLES["dotnet|3.1|product-version"]}}-{{OS_VERSION}}

COPY --from=installer ["/dotnet/shared/Microsoft.AspNetCore.App", "/Program Files/dotnet/shared/Microsoft.AspNetCore.App"]
