jobs:
- job: Build
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  steps:
  - task: CodeQL3000Init@0
    displayName: CodeQL Initialize
  - script: >
      find . -name '*.csproj' | grep $(cgBuildGrepArgs) | xargs -n 1 dotnet build
    displayName: Build Projects
  - task: CodeQL3000Finalize@0
    displayName: CodeQL Finalize
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: Component Detection
