parameters:
  name: null
  pool: {}
  additionalOptions: null
  publicProjectName: null
  customInitSteps: []

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - template: /eng/common/templates/steps/init-docker-linux.yml@self
  - ${{ parameters.customInitSteps }}
  - template: /eng/common/templates/steps/copy-base-images.yml@self
    parameters:
      additionalOptions: ${{ parameters.additionalOptions }}
      publicProjectName: ${{ parameters.publicProjectName }}
      continueOnError: true
