parameters:
  pool: {}

jobs:
- job: GenerateSBOM
  pool: ${{ parameters.pool }}
  strategy:
    matrix:
      amd64:
        arch: amd64
      arm32:
        arch: arm
      arm64:
        arch: arm64
  variables:
    sbomDirectory: $(Build.ArtifactStagingDirectory)/sbom
  steps:
  - template: ../steps/init-docker-linux.yml
  - template: ../steps/download-build-artifact.yml
    parameters:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: image-info
  - script: >
      $(runImageBuilderCmd) trimUnchangedPlatforms
      '$(artifactsPath)/image-info.json'
    displayName: Trim Unchanged Images
  - script: >
      $(runImageBuilderCmd) pullImages
      --architecture '$(arch)'
      --manifest 'manifest.json'
      --output-var 'pulledImages'
      --image-info '$(artifactsPath)/image-info.json'
    name: PullImages
    displayName: Pull Images
  - script: mkdir $(sbomDirectory)
    displayName: Create SBOM Directory
  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: Generate SBOM
    inputs:
      PackageName: ".NET"
      PackageVersion: $(Build.BuildNumber)
      BuildDropPath: $(Build.ArtifactStagingDirectory)
      ManifestDirPath: $(sbomDirectory)
      dockerImagesToScan: $(PullImages.pulledImages)
  - publish: $(sbomDirectory)
    artifact: sbom_linux_$(arch)
    displayName: Publish SBOM
