parameters:
  matrixType: null
  name: null
  pool: {}
  customBuildLegGroupArgs: ""
  isTestStage: false
  internalProjectName: null

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - template: /eng/common/templates/steps/retain-build.yml@self
  - template: /eng/common/templates/steps/init-docker-linux.yml@self
  - template: /eng/common/templates/steps/validate-branch.yml@self
    parameters:
      internalProjectName: ${{ parameters.internalProjectName }}
  - ${{ if eq(parameters.isTestStage, true) }}:
    - template: /eng/common/templates/steps/download-build-artifact.yml@self
      parameters:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: image-info
    - script: echo "##vso[task.setvariable variable=additionalGenerateBuildMatrixOptions]--image-info $(artifactsPath)/image-info.json"
      displayName: Set GenerateBuildMatrix Variables
  - ${{ if eq(parameters.isTestStage, false) }}:
    - script: echo "##vso[task.setvariable variable=additionalGenerateBuildMatrixOptions]"
      displayName: Set GenerateBuildMatrix Variables
  - script: >
      $(runImageBuilderCmd) generateBuildMatrix
      --manifest $(manifest)
      --type ${{ parameters.matrixType }}
      --os-type '*'
      --architecture '*'
      --product-version-components $(productVersionComponents)
      ${{ parameters.customBuildLegGroupArgs }}
      $(imageBuilder.pathArgs)
      $(manifestVariables)
      $(additionalGenerateBuildMatrixOptions)
    displayName: Generate ${{ parameters.matrixType }} Matrix
    name: matrix
