parameters:
  matrixType: null
  name: null
  customBuildLegGroupArgs: ""
  isTestStage: false

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  steps:
  - template: ../steps/validate-branch.yml
  - template: ../steps/init-docker-linux.yml
  - ${{ if eq(parameters.isTestStage, true) }}:
    - template: ../steps/download-build-artifact.yml
      parameters:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: image-info
    - script: echo "##vso[task.setvariable variable=additionalGenerateBuildMatrixOptions]--image-info $(artifactsPath)/image-info.json"
      displayName: Set GenerateBuildMatrix Variables
  - script: >
      $(runImageBuilderCmd) generateBuildMatrix
      --manifest $(manifest)
      --type ${{ parameters.matrixType }}
      --os-type '*'
      --architecture '*'
      --product-version-components $(productVersionComponents)
      ${{ parameters.customBuildLegGroupArgs }}
      $(imageBuilder.pathArgs)
      $(manifestVariables)
      $(additionalGenerateBuildMatrixOptions)
    displayName: Generate ${{ parameters.matrixType }} Matrix
    name: matrix
  - template: ../steps/cleanup-docker-linux.yml
