parameters:
  pool: {}
  internalProjectName: null
  customInitSteps: []
  customPublishVariables: []

jobs:
- job: Publish
  pool: ${{ parameters.pool }}
  variables:
  - name: imageBuilder.commonCmdArgs
    value: >
      --manifest '$(manifest)'
      --registry-override '$(acr.server)'
      $(manifestVariables)
      $(imageBuilder.queueArgs)
  - name: publishNotificationRepoName
    value: $(Build.Repository.Name)
  - name: branchName
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
      value: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
      value: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
  - ${{ parameters.customPublishVariables }}
  steps:
  - template: /eng/common/templates/steps/retain-build.yml@self
  - template: /eng/common/templates/steps/init-docker-linux.yml@self
  - pwsh: |
      $azdoOrgName = Split-Path -Leaf $Env:SYSTEM_COLLECTIONURI
      echo "##vso[task.setvariable variable=azdoOrgName]$azdoOrgName"
    displayName: Set Publish Variables
  - ${{ parameters.customInitSteps }}
  - template: /eng/common/templates/steps/validate-branch.yml@self
    parameters:
      internalProjectName: ${{ parameters.internalProjectName }}
  - template: /eng/common/templates/steps/download-build-artifact.yml@self
    parameters:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: image-info
  - template: /eng/common/templates/steps/set-image-info-path-var.yml@self
    parameters:
      publicSourceBranch: $(publicSourceBranch)
  - template: /eng/common/templates/steps/set-dry-run.yml@self
  - script: echo $(sourceBuildId) > $(Build.ArtifactStagingDirectory)/source-build-id.txt
    displayName: Write Source Build ID to File
  - template: /eng/common/templates/steps/publish-artifact.yml@self
    parameters:
      path: $(Build.ArtifactStagingDirectory)/source-build-id.txt
      artifactName: source-build-id
      displayName: Publish Source Build ID Artifact
      internalProjectName: ${{ parameters.internalProjectName }}
      publicProjectName: ${{ parameters.publicProjectName }}
  - script: echo "##vso[task.setvariable variable=imageQueueTime]$(date --rfc-2822)"
    displayName: Set Publish Variables
  - script: >
      $(runImageBuilderCmd) trimUnchangedPlatforms
      '$(artifactsPath)/image-info.json'
    displayName: Trim Unchanged Images
  - script: >
      $(runImageBuilderCmd) copyAcrImages
      '$(acr.servicePrincipalName)'
      '$(acr.servicePrincipalPassword)'
      '$(acr.servicePrincipalTenant)'
      '$(acr.subscription)'
      '$(acr.resourceGroup)'
      '$(stagingRepoPrefix)'
      --os-type '*'
      --architecture '*'
      --repo-prefix '$(publishRepoPrefix)'
      --image-info '$(artifactsPath)/image-info.json'
      $(dryRunArg)
      $(imageBuilder.pathArgs)
      $(imageBuilder.commonCmdArgs)
    displayName: Copy Images
  - script: >
      $(runImageBuilderCmd) publishManifest
      '$(artifactsPath)/image-info.json'
      --repo-prefix '$(publishRepoPrefix)'
      --registry-creds '$(acr.server)=$(acr.userName);$(acr.password)'
      --os-type '*'
      --architecture '*'
      $(dryRunArg)
      $(imageBuilder.pathArgs)
      $(imageBuilder.commonCmdArgs)
    displayName: Publish Manifest
  - template: /eng/common/templates/steps/publish-artifact.yml@self
    parameters:
      path: $(Build.ArtifactStagingDirectory)/image-info.json
      artifactName: image-info-final-$(System.JobAttempt)
      displayName: Publish Image Info File Artifact
      internalProjectName: ${{ parameters.internalProjectName }}
      publicProjectName: ${{ parameters.publicProjectName }}
  - template: /eng/common/templates/steps/wait-for-mcr-image-ingestion.yml@self
    parameters:
      imageInfoPath: '$(artifactsPath)/image-info.json'
      minQueueTime: $(imageQueueTime)
      dryRunArg: $(dryRunArg)
      condition: succeeded()
  - template: /eng/common/templates/steps/publish-readmes.yml@self
    parameters:
      dryRunArg: $(dryRunArg)
      condition: and(succeeded(), eq(variables['publishReadme'], 'true'))
  - script: >
      $(runImageBuilderCmd) publishImageInfo
      '$(artifactsPath)/image-info.json'
      '$(gitHubVersionsRepoInfo.userName)'
      '$(gitHubVersionsRepoInfo.email)'
      '$(gitHubVersionsRepoInfo.accessToken)'
      --git-owner '$(gitHubVersionsRepoInfo.org)'
      --git-repo '$(gitHubVersionsRepoInfo.repo)'
      --git-branch '$(gitHubVersionsRepoInfo.branch)'
      --git-path '$(gitHubImageInfoVersionsPath)'
      $(dryRunArg)
      $(imageBuilder.commonCmdArgs)
    condition: and(succeeded(), eq(variables['publishImageInfo'], 'true'))
    displayName: Publish Image Info
  - script: >
      $(runImageBuilderCmd) ingestKustoImageInfo
      '$(artifactsPath)/image-info.json'
      '$(kusto.cluster)'
      '$(kusto.database)'
      '$(kusto.imageTable)'
      '$(kusto.layerTable)'
      '$(kusto.servicePrincipalName)'
      '$(kusto.servicePrincipalPassword)'
      '$(kusto.servicePrincipalTenant)'
      --os-type '*'
      --architecture '*'
      $(dryRunArg)
      $(imageBuilder.commonCmdArgs)
    displayName: Ingest Kusto Image Info
    condition: and(succeeded(), eq(variables['ingestKustoImageInfo'], 'true'))
  - script: >
      $(runImageBuilderCmd) postPublishNotification
      '$(publishNotificationRepoName)'
      '$(branchName)'
      '$(artifactsPath)/image-info.json'
      $(Build.BuildId)
      '$(System.AccessToken)'
      '$(azdoOrgName)'
      '$(System.TeamProject)'
      '$(gitHubNotificationsRepoInfo.accessToken)'
      '$(gitHubNotificationsRepoInfo.org)'
      '$(gitHubNotificationsRepoInfo.repo)'
      --repo-prefix '$(publishRepoPrefix)'
      --task "Copy Images"
      --task "Publish Manifest"
      --task "Wait for Image Ingestion"
      --task "Publish Readmes"
      --task "Wait for MCR Doc Ingestion"
      --task "Publish Image Info"
      --task "Ingest Kusto Image Info"
      $(dryRunArg)
      $(imageBuilder.commonCmdArgs)
    displayName: Post Publish Notification
    condition: and(always(), eq(variables['publishNotificationsEnabled'], 'true'))
  - template: /eng/common/templates/steps/cleanup-docker-linux.yml@self
