parameters:
  name: null
  pool: {}
  matrix: {}
  testJobTimeout: 60
  internalProjectName: null
  customInitSteps: []

jobs:
- job: ${{ parameters.name }}
  condition: and(succeeded(), ${{ parameters.matrix }})
  dependsOn: GenerateTestMatrix
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  timeoutInMinutes: ${{ parameters.testJobTimeout }}
  steps:
  - template: /eng/common/templates/steps/test-images-windows-client.yml@self
    parameters:
      internalProjectName: ${{ parameters.internalProjectName }}
      customInitSteps: ${{ parameters.customInitSteps }}
