jobs:
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  # Split the Linux images into separate jobs in order to compensate for less
  # disk space on the Linux agents. See https://github.com/dotnet/dotnet-docker/issues/1588
  - job: LinuxAmd64PerfTests
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    workspace:
      clean: all
    steps:
    - template: ../steps/validate-image-sizes.yml
      parameters:
        dockerClientOS: linux
        architecture: amd64
        validationMode: size
  - job: LinuxArmPerfTests
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    workspace:
      clean: all
    steps:
    - template: ../steps/validate-image-sizes.yml
      parameters:
        dockerClientOS: linux
        architecture: arm*
        validationMode: size
- job: LinuxBaselineIntegrityPerfTests
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  workspace:
    clean: all
  steps:
  - template: ../steps/validate-image-sizes.yml
    parameters:
      dockerClientOS: linux
      validationMode: integrity
- job: WindowsPerfTests
  pool: Docker-20H2-${{ variables['System.TeamProject'] }}
  workspace:
    clean: all
  steps:
  - template: ../steps/validate-image-sizes.yml
    parameters:
      dockerClientOS: windows
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        validationMode: integrity
