jobs:
- job: WaitForIngestion
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  steps:
  - template: ../steps/init-docker-linux.yml
  - template: ../steps/download-build-artifact.yml
    parameters:
      targetPath: $(Build.ArtifactStagingDirectory)
      condition: and(succeeded(), ne(variables['sourceBuildId'], ''))
  - powershell: |
      # Get the last image info artifact that was published
      $imageInfoDirName = @($(dir $(Build.ArtifactStagingDirectory)/image-info-final-* | select -ExpandProperty Name))[-1]
      $imageInfoPath = "$(artifactsPath)/$imageInfoDirName/image-info.json"
      echo "##vso[task.setvariable variable=imageInfoPath]$imageInfoPath"
    displayName: Get Image Info Path
    condition: and(succeeded(), ne(variables['sourceBuildId'], ''))
  - template: ../steps/wait-for-mcr-image-ingestion.yml
    parameters:
      imageInfoPath: $(imageInfoPath)
      minQueueTime: $(minQueueTime)
      condition: and(succeeded(), ne(variables['sourceBuildId'], ''))
  - template: ../steps/wait-for-mcr-doc-ingestion.yml
    parameters:
      commitDigest: $(readmeCommitDigest)
      condition: and(succeeded(), ne(variables['readmeCommitDigest'], ''))
  - template: ../steps/cleanup-docker-linux.yml
