aliveStatusCodes:
  - 200
  - 406
dirs:
  - .
  - .github
excludedDirs:
  - eng/readme-templates
ignorePatterns:
  - pattern: "^https://github.com/microsoft/mcr.*$"
  - pattern: "^https://github.com/dotnet/release.*$"
useGitIgnore: true
