aliveStatusCodes:
  - 200 # OK
  - 406 # Not acceptable: server cannot provide a suitable representation for the specified `Accept` header
  # All GitHub links give status code 429 as of 2025-04-25.
  # Tracking issue: https://github.com/UmbrellaDocs/action-linkspector/issues/43
  # Remove status code 429 from this list when that issue is resolved.
  - 429 # Too many requests
dirs:
  - .
  - .github
excludedDirs:
  - eng/readme-templates
ignorePatterns:
  - pattern: "^https://github.com/microsoft/mcr.*$"
  - pattern: "^https://github.com/dotnet/release.*$"
  - pattern: "^https://aka.ms/$"
  # This link often fails with a 504 error - it's known good, though.
  - pattern: "^https://canonical.com/blog/canonical-releases-ubuntu-24-04-noble-numbat$"
useGitIgnore: true
