parameters:
  customPublishInitSteps: []
  customPublishVariables: []

  internalProjectName: null
  publicProjectName: null

  publishConfig: null

  isStandalonePublish: false

  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)

  sourceBuildPipelineDefinitionId: ''
  sourceBuildPipelineRunId: ''

  versionsRepoRef: null
  versionsRepoPath: "versions"

  # When true, any updated images will have the SHA in their commit URL updated
  # to the commit that this pipeline is running on, instead of the commit they
  # were built from. Use in combination with isStandalonePublish to ensure that
  # internally built images still reference public Dockerfiles.
  overrideImageInfoCommit: false

################################################################################
# Publish Images
################################################################################
stages:
- stage: Publish
  ${{ if eq(parameters.isStandalonePublish, true) }}:
    dependsOn: []
  ${{ else }}:
    ${{ if and(eq(variables['System.TeamProject'], parameters.internalProjectName), ne(variables['Build.Reason'], 'PullRequest')) }}:
      dependsOn: Test
    ${{ else }}:
      dependsOn: Post_Build
  condition: "
    and(
      not(canceled()),
      and(
        contains(variables['stages'], 'publish'),
        or(
          or(
            and(
              and(
                contains(variables['stages'], 'build'),
                succeeded('Post_Build')),
              and(
                contains(variables['stages'], 'test'),
                in(dependencies.Test.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'))),
            or(
              and(
                not(contains(variables['stages'], 'build')),
                and(
                  contains(variables['stages'], 'test'),
                  in(dependencies.Test.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'))),
              and(
                not(contains(variables['stages'], 'test')),
                and(
                  contains(variables['stages'], 'build'),
                  succeeded('Post_Build'))))),
          not(
            or(
              contains(variables['stages'], 'build'),
              contains(variables['stages'], 'test'))))))"
  jobs:
  - template: /eng/docker-tools/templates/jobs/publish.yml@self
    parameters:
      pool: ${{ parameters.pool }}
      internalProjectName: ${{ parameters.internalProjectName }}
      publishConfig: ${{ parameters.publishConfig }}
      customPublishVariables: ${{ parameters.customPublishVariables }}
      customInitSteps: ${{ parameters.customPublishInitSteps }}
      sourceBuildPipelineDefinitionId: ${{ parameters.sourceBuildPipelineDefinitionId }}
      sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
      versionsRepoRef: ${{ parameters.versionsRepoRef }}
      versionsRepoPath: ${{ parameters.versionsRepoPath }}
      overrideImageInfoCommit: ${{ parameters.overrideImageInfoCommit }}
