# This pipelines builds all projects in the repository outside of Dockerfiles so that the artifacts
# can be scanned by SDL steps.  SDL steps do not scan artifacts that are built within Dockerfiles.
trigger:
  branches:
    include:
    - main
    - nightly
pr: none

parameters:
# Setting CG Dry Run will run detection and submit results, but only for non-production branches, preventing scan
# results from being officially registered.
- name: cgDryRun
  type: boolean
  default: false
  displayName: CG Dry Run

variables:
- template: /eng/docker-tools/templates/variables/common.yml@self
- name: skipComponentGovernanceDetection
  value: false

extends:
  template: /eng/docker-tools/templates/1es-official.yml@self
  parameters:
    stages:
    - stage: CgDetection
      displayName: CG Detection
      jobs:
      - template: /eng/docker-tools/templates/jobs/cg-build-projects.yml@self
        parameters:
          # This should match the latest .NET version used across all projects in the repo, including samples.
          # Otherwise, the pipeline will fail to build projects.
          dotnetVersionChannel: '10.0'
          cgDryRun: ${{ parameters.cgDryRun }}
