# This pipelines builds all projects in the repository outside of Dockerfiles so that the artifacts
# can be scanned by SDL steps.  SDL steps do not scan artifacts that are built within Dockerfiles.
trigger:
  branches:
    include:
    - main
    - nightly
pr: none

variables:
- template: /eng/common/templates/variables/common.yml@self
- name: skipComponentGovernanceDetection
  value: false

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - stage: CgDetection
      displayName: CG Detection
      jobs:
      - template: /eng/common/templates/jobs/cg-build-projects.yml@self
