trigger: none
pr: none

schedules:
- cron: "0 12 * * Sun"
  displayName: Weekend build
  branches:
    include:
    - main
    - nightly
  always: true

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- template: /eng/common/templates/variables/common.yml@self
- name: ComponentDetection.Timeout
  value: 3600 # 1 hour in seconds

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-ubuntu-2204
      os: linux
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
    stages:
    - stage: cg
      displayName: CG Detection (Docker Images)
      jobs:
      - job: ScanImages
        displayName: Scan Images
        strategy:
            matrix:
              amd64:
                arch: amd64
              arm32:
                arch: arm
              arm64:
                arch: arm64
        steps:
        - template: /eng/common/templates/steps/init-docker-linux.yml@self
          parameters:
            cleanupDocker: true
        - script: >
            $(runImageBuilderCmd) pullImages
            --architecture '$(arch)'
            --manifest 'manifest.json'
            --output-var 'pulledImages'
          displayName: Pull Images
          name: PullImages
        - task: ComponentGovernanceComponentDetection@0
          inputs:
            dockerImagesToScan: $(PullImages.pulledImages)
          displayName: Detect Components
        - template: /eng/common/templates/steps/cleanup-docker-linux.yml@self
