trigger: none
pr:
  branches:
    include:
    - master
    - nightly
  paths:
    include:
    - manifest.samples.json
    - eng/*
    - samples/*
    - tests/*

resources:
  repositories:
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - repository: VersionsRepo
      type: github
      endpoint: dotnet
      name: dotnet/versions

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.samples.json
- name: repoTestArgs
  value: -TestCategories sample
- name: imageInfoVariant
  value: "-samples"
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      buildMatrixType: platformVersionedOs
      buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build
