trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - manifest.json
    - manifest.versions.json
    - eng/*
    - src/*
    - tests/*

variables:
- template: /eng/pipelines/variables/core-official.yml@self

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

stages:
- template: /eng/common/templates/stages/dotnet/publish-config-prod.yml@self
  parameters:
    stagesTemplate: /eng/pipelines/stages/build-test-publish-repo.yml@self
    stagesTemplateParameters:
      versionsRepoRef: VersionsRepo
