trigger: none
pr: none

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.samples.json
- name: repoTestArgs
  value: -TestCategories sample
- name: imageInfoVariant
  value: "-samples"
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
