trigger: none
pr:
  branches:
    include:
    - main
    - nightly
  paths:
    include:
    - manifest.samples.json
    - eng/*
    - samples/*
    - tests/*

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/samples.yml

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    buildMatrixType: platformVersionedOs
    buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build
