trigger: none
pr:
  branches:
    include:
    - master
    - nightly
  paths:
    include:
    - eng/*
    - samples/*
    - tests/*
variables:
- template: variables/common.yml
- name: manifest
  value: manifest.samples.json
- name: repoTestArgs
  value: -TestCategories sample
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      buildMatrixType: platformVersionedOs
