trigger: none
pr:
  branches:
    include:
    - nightly
  paths:
    include:
    - eng/*
    - tests/*

variables:
- template: /eng/pipelines/variables/core-unofficial.yml

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

stages:
- template: /eng/common/templates/stages/dotnet/publish-config-nonprod.yml@self
  parameters:
    stagesTemplate: /eng/pipelines/stages/build-test-publish-repo.yml@self
    stagesTemplateParameters:
      versionsRepoRef: VersionsRepo
      noCache: true
