trigger: none
pr:
  branches:
    include:
    - nightly
  paths:
    include:
    - eng/*
    - tests/*

resources:
  repositories:
  - repository: PublicVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/core.yml

stages:
- template: stages/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    noCache: true
