trigger: none
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/samples.yml

stages:
- template: stages/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
