trigger: none
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: git
    name: internal/dotnet-versions

variables:
- template: variables/core.yml

stages:
- template: stages/build-test-publish-repo.yml
