trigger: none
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - documentation/*
    - README*
    - samples/*

variables:
- template: variables/common.yml
- name: manifest
  value: manifest.json
stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      buildMatrixType: platformVersionedOs
      customBuildLegGrouping: pr-build
