trigger: none
pr: none

schedules:
- cron: "0 5 * * 1"
  displayName: Weekly build
  branches:
    include:
    - nightly

variables:
- template: variables/common.yml

jobs:
- job: LinuxPerfTests
  pool: Hosted Ubuntu 1604
  workspace:
    clean: all
  steps:
  - template: ../common/templates/steps/cleanup-docker-linux.yml
  - powershell: ./tests/performance/Validate-ImageSize.ps1
    displayName: Run Image Size Tests
  - template: ../common/templates/steps/cleanup-docker-linux.yml
- job: WindowsPerfTests
  pool: # windows1903Amd64
    name: DotNetCore-Docker
    demands: VSTS_OS -equals Windows_Server_2019_Data_Center_1903
  workspace:
    clean: all
  steps:
  - template: ../common/templates/steps/cleanup-docker-windows.yml
  - powershell: ./tests/performance/Validate-ImageSize.ps1
    displayName: Run Image Size Tests
  - template: ../common/templates/steps/cleanup-docker-windows.yml
