trigger: none
pr:
  branches:
    include:
    - nightly
  paths:
    exclude:
    - .github/*
    - documentation/*
    - README*
    - samples/*

variables:
- template: ../common/templates/variables/dotnet/common.yml

jobs:
- template: ../common/templates/jobs/validate-image-sizes.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
