trigger: none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - manifest.json
    - eng/*
    - src/aspnet/3.1/*
    - src/runtime/3.1/*
    - src/runtime-deps/3.1/*
    - src/sdk/3.1/*
    - tests/*

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/core.yml
- name: imageBuilder.pathArgs
  value: --path 'src/*/3.1/*'

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    buildMatrixType: platformVersionedOs
    buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build --custom-build-leg-group test-dependencies
