trigger: none
pr: none

variables:
- template: variables/core.yml

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    testMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies
