trigger: none
pr:
  branches:
    include:
    - nightly
  paths:
    include:
    - '*'
    exclude:
    - samples/*

variables:
- template: variables/common.yml

jobs:
- template: ../common/templates/jobs/validate-image-sizes.yml
