# This pipeline is a work in progress.
# See https://github.com/dotnet/dotnet-docker-internal/issues/8566 for more details.

trigger: none
pr: none

parameters:
- name: sourceBuildPipelineRunId
  displayName: >
    Source build pipeline run ID. This refers to runs of *this pipeline*.
    Override this parameter in combination with disabling the `Build` stage to
    test or publish images that were built in a different pipeline run. When
    building new images, leave this value alone.
  type: string
  default: $(Build.BuildId)

variables:
- template: /eng/pipelines/variables/core.yml@self
  parameters:
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
- name: officialBranches
  # comma-delimited list of branch names
  value: nightly

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

extends:
  template: /eng/common/templates/1es-unofficial.yml@self
  parameters:
    stages:
    - template: /eng/pipelines/stages/build-test-publish-repo.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        versionsRepoRef: VersionsRepo
        sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
