trigger: none
pr: none

schedules:
- cron: "0 5 * * 1"
  displayName: Weekly build
  branches:
    include:
    - nightly
  always: true
variables:
- template: ../common/templates/variables/dotnet/common.yml

jobs:
- template: ../common/templates/jobs/validate-image-sizes.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
