trigger: none
# This pipeline is intended to be run for internal PRs only in AzDO.
# Configuring the pipeline to run for PRs in AzDO is not supported from the YAML but instead
# is configured through the build validation policy for the appropriate branch.
# https://docs.microsoft.com/azure/devops/pipelines/troubleshooting/troubleshooting?view=azure-devops#pull-request-triggers-not-supported-with-azure-repos
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/dotnet-docker-internal

variables:
- template: variables/internal-core.yml

stages:
- template: stages/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
