trigger: none
pr:
  branches:
    include:
    - nightly
  paths:
    include:
    - eng/*
    - tests/*

variables:
- template: variables/core.yml

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

stages:
- template: stages/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    versionsRepoRef: VersionsRepo
    noCache: true
