trigger: none
pr:
  branches:
    include:
    - main
    - nightly
  paths:
    include:
    - manifest.samples.json
    - eng/*
    - samples/*
    - tests/*
    exclude:
    - eng/update-dependencies

variables:
- template: /eng/pipelines/variables/samples.yml@self
- name: publishEolAnnotations
  value: false
  readonly: true

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

stages:
- template: /eng/common/templates/stages/dotnet/publish-config-nonprod.yml@self
  parameters:
    stagesTemplate: /eng/pipelines/stages/build-test-publish-repo.yml@self
    stagesTemplateParameters:
      versionsRepoRef: VersionsRepo
