trigger: none
pr:
  branches:
    include:
    - nightly
    - feature/*
  paths:
    include:
    - manifest.json
    - eng/*
    - src/monitor/*
    - tests/*

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/core.yml
- name: imageBuilder.pathArgs
  value: --path 'src/*/3.1/alpine*/amd64' --path 'src/monitor/*'

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    buildMatrixType: platformVersionedOs
    buildMatrixCustomBuildLegGroupArgs: --custom-build-leg-group pr-build --custom-build-leg-group test-dependencies
