trigger: none
pr: none

resources:
  pipelines:
  - pipeline: dotnet-docker-release-staging
    source: dotnet-docker-release-staging

variables:
- template: /eng/pipelines/variables/core.yml@self
  parameters:
    sourceBuildPipelineRunId: "$(resources.pipeline.dotnet-docker-release-staging.runID)"
# Set pathArgs to empty in order to publish all images
- name: imageBuilder.pathArgs
  value: ""
- name: imageBuilder.queueArgs
  value: ""

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - template: /eng/pipelines/stages/publish.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        isStandalonePublish: true
        # Only allow the dotnet-docker-release-staging pipeline as a source for publishing
        # https://dev.azure.com/dnceng/internal/_build?definitionId=1434
        sourceBuildPipelineDefinitionId: "1434"
        sourceBuildPipelineRunId: "$(resources.pipeline.dotnet-docker-release-staging.runID)"
        customPublishInitSteps:
        - script: echo "##vso[task.setvariable variable=sourceBuildId]$(resources.pipeline.dotnet-docker-release-staging.runID)"
          displayName: Set sourceBuildId
