# This pipeline takes the current branch and builds and tests the images,
# but does not publish them.
#
# The images can later be published by running the release-promotion pipeline.

trigger: none
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

parameters:
- name: sourceBuildPipelineRunId
  displayName: >
    Source build pipeline run ID. This refers to runs of *this pipeline*.
    Override this parameter in combination with disabling the `Build` stage to
    test images that were built in a different pipeline run. When
    building new images, leave this value alone.
  type: string
  default: $(Build.BuildId)

variables:
- template: /eng/pipelines/variables/core.yml@self
  parameters:
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    serviceConnections:
    - name: $(internal-mirror.serviceConnectionName)
    - name: $(build.serviceConnectionName)
    - name: $(dotnetstaging.serviceConnectionName)
    stages:
    - template: /eng/pipelines/stages/build-and-test.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
        isInternalServicingValidation: true
        # We always want staged images to be as up-to-date as possible,
        # so don't rely on any caching behavior.
        noCache: true
