trigger: none
pr: none

variables:
- template: /eng/pipelines/variables/core-unofficial.yml@self
# Always run only the publish stage
- name: stages
  value: "publish"
  readonly: true
# Set pathArgs to empty in order to publish all images
- name: imageBuilder.pathArgs
  value: ""
- name: imageBuilder.queueArgs
  value: ""
- name: gitHubVersionsRepoInfo.org
  value: dotnet
- name: gitHubVersionsRepoInfo.repo
  value: dotnet-docker-internal
- name: gitHubVersionsRepoInfo.branch
  value: main

resources:
  pipelines:
  - pipeline: release-staging
    source: dotnet-docker-release-staging-unofficial
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/dotnet-docker-internal
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

extends:
  template: /eng/docker-tools/templates/1es.yml@self
  parameters:
    reposToExcludeFromScanning:
    - VersionsRepo
    stages:
    - template: /eng/docker-tools/templates/stages/dotnet/publish-config-nonprod.yml@self
      parameters:
        sourceBuildPipelineRunId: "$(resources.pipeline.release-staging.runID)"
        stagesTemplate: /eng/pipelines/stages/publish.yml@self
        stagesTemplateParameters:
          versionsRepoRef: VersionsRepo
          isStandalonePublish: true
          # Whenever staged images are published, we need to override the commit SHA since they were
          # staged from an earlier, internal commit. We want the image info's commit URLs to point to
          # the commit that this pipeline is running on, which should be the latest commit on the
          # main branch.
          overrideImageInfoCommit: true
          sourceBuildPipelineDefinitionId: "$(resources.pipeline.release-staging.pipelineID)"
          sourceBuildPipelineRunId: "$(resources.pipeline.release-staging.runID)"
          customPublishInitSteps:
          - script: echo "##vso[task.setvariable variable=sourceBuildId]$(resources.pipeline.release-staging.runID)"
            displayName: Set sourceBuildId
