trigger: none
pr: none

resources:
  repositories:
  pipelines:
  - pipeline: dotnet-docker-release-staging-pipeline
    source: dotnet-docker-release-staging

variables:
- template: /eng/pipelines/variables/core.yml@self

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - template: /eng/pipelines/stages/publish.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        # We always want staged images to be as up-to-date as possible,
        # so don't rely on any caching behavior.
        noCache: true
