trigger: none
pr: none

resources:
  pipelines:
  - pipeline: dotnet-docker-release-staging
    source: dotnet-docker-release-staging

variables:
- template: /eng/pipelines/variables/core.yml@self

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - template: /eng/pipelines/stages/publish.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        # We always want staged images to be as up-to-date as possible,
        # so don't rely on any caching behavior.
        noCache: true
        customPublishInitSteps:
        - script: |
            echo $(resources.pipeline.dotnet-docker-release-staging.pipelineID)
            echo $(resources.pipeline.dotnet-docker-release-staging.runName)
            echo $(resources.pipeline.dotnet-docker-release-staging.runID)
            echo $(resources.pipeline.dotnet-docker-release-staging.runURI)
            echo $(resources.pipeline.dotnet-docker-release-staging.sourceBranch)
            echo $(resources.pipeline.dotnet-docker-release-staging.sourceCommit)
            echo $(resources.pipeline.dotnet-docker-release-staging.sourceProvider)
            echo $(resources.pipeline.dotnet-docker-release-staging.requestedFor)
            echo $(resources.pipeline.dotnet-docker-release-staging.requestedForID)
          displayName: Check Pipeline Resource Variables
