trigger: none
pr: none

extends:
  template: /eng/common/templates/1es-official.yml@self
  stages:
  - stage: release-promotion
    jobs:
    - job: release-promotion
      steps:
      - script: echo "Hello world"
