# This pipeline takes the current branch and builds and tests the images,
# but does not publish them.
#
# The images can later be published by running the release-promotion pipeline.

trigger: none
pr: none

parameters:
- name: sourceBuildPipelineRunId
  displayName: >
    Source build pipeline run ID. This refers to runs of *this pipeline*.
    Override this parameter in combination with disabling the `Build` stage to
    test images that were built in a different pipeline run. When
    building new images, leave this value alone.
  type: string
  default: $(Build.BuildId)
- name: noCache
  displayName: >
    Disable image caching. By default, an image is built only when its
    Dockerfile was modified or its base image has been updated. Setting this
    parameter to true forces all images to be built (except those excluded by
    path arguments).
  type: boolean
  default: false

variables:
- template: /eng/pipelines/variables/core.yml@self
  parameters:
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    serviceConnections:
    - name: $(internal-mirror.serviceConnectionName)
    - name: $(build.serviceConnectionName)
    - name: $(dotnetstaging.serviceConnectionName)
    stages:
    - template: /eng/pipelines/stages/build-and-test.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        versionsRepoRef: VersionsRepo
        sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
        isInternalServicingValidation: true
        noCache: ${{ parameters.noCache }}
