trigger: none

schedules:
- cron: 0 12 * * 0
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: true

stages:
- stage: SynchronizeSecrets
  jobs:
  - job: Synchronize
    displayName: Synchronize secrets
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2022

    steps:
    - task: UseDotNet@2
      displayName: Install .NET 8.0 SDK
      inputs:
        packageType: sdk
        version: 8.0.x
        installationPath: '$(Build.Repository.LocalPath)/.dotnet'

    - task: UseDotNet@2
      displayName: Install .NET 6.0 runtime
      inputs:
        packageType: runtime
        version: 6.0.x
        installationPath: '$(Build.Repository.LocalPath)/.dotnet'

    - powershell: .dotnet/dotnet tool restore --tool-manifest .config/dotnet-tools.json
      workingDirectory: $(Build.Repository.LocalPath)
      displayName: Restore secret-manager

    - task: AzureCLI@2
      inputs:
        azureSubscription: DotNet Eng Services Secret Manager
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          Get-ChildItem .vault-config/*.yaml |% { .dotnet/dotnet secret-manager synchronize $_}
        workingDirectory: $(Build.Repository.LocalPath)
      displayName: Run secret-manager synchronize
