trigger: none
pr: none

parameters:
- name: sourceBranch
  displayName: Source Branch (public)
  type: string
- name: targetBranch
  displayName: Target Branch (internal)
  type: string

variables:
- template: /eng/common/templates/variables/dotnet/common.yml@self
- group: DotNet-Docker-Common-2
# Always run unofficial pipelines in debug mode
- name: "System.Debug"
  value: true
  readonly: true

extends:
  template: /eng/common/templates/1es.yml@self
  parameters:
    stages:
    - stage: SyncReleaseBranchesStage
      displayName: Sync Release Branches

      jobs:
      - job: SyncReleaseBranchesJob
        displayName: Sync Release Branches
        pool:
          name: $(default1ESInternalPoolName)
          image: $(default1ESInternalPoolImage)
          os: linux

        steps:
        - checkout: self
          fetchDepth: 1

        - template: /eng/pipelines/steps/install-dotnet.yml@self

        - task: AzureCLI@2
          displayName: Sync Release Branches
          inputs:
            azureSubscription: "$(updateDepsInt-test.serviceConnectionName)"
            scriptType: "pscore"
            scriptLocation: "inlineScript"
            addSpnToEnvironment: true
            inlineScript: >-
              dotnet run --configuration Release --project ./eng/update-dependencies/update-dependencies.csproj --
              sync-internal-release
              --azdo-organization "$env:SYSTEM_COLLECTIONURI"
              --azdo-project "$env:SYSTEM_TEAMPROJECT"
              --azdo-repo "$env:BUILD_REPOSITORY_NAME"
              --source-branch "${{ parameters.sourceBranch }}"
              --target-branch "${{ parameters.targetBranch }}"
              --pr-branch-prefix "pr"
              --user "$env:DOTNETDOCKERBOT_USERNAME"
              --email "$env:DOTNETDOCKERBOT_EMAIL"
              --staging-storage-account "dotnetstage"
