trigger: none
pr: none

parameters:
- name: sourceBranch
  displayName: Source Branch (public)
  type: string
- name: targetBranch
  displayName: Target Branch (internal)
  type: string

variables:
- template: /eng/docker-tools/templates/variables/dotnet/common.yml@self
- group: DotNet-Docker-Common-2
# Always run unofficial pipelines in debug mode
- name: "System.Debug"
  value: true
  readonly: true

extends:
  template: /eng/pipelines/pipelines/sync-internal-release.yml@self
  parameters:
    sourceBranch: ${{ parameters.sourceBranch }}
    targetBranch: ${{ parameters.targetBranch }}
    # Service connection used to push new branches and submit pull requests.
    serviceConnection: "$(updateDepsInt-test.serviceConnectionName)"
