trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true
variables:
- template: ../common/templates/variables/dotnet/common.yml
stages:
- stage: Monitor
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/dotnet-monitor)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    strategy:
      matrix:
        Update6:
          MajorMinorVersion: 6.$(monitor6MinorVersion)
          ChannelQuality: $(monitor6Quality)
        Update7:
          MajorMinorVersion: 7.$(monitor7MinorVersion)
          ChannelQuality: $(monitor7Quality)
        Update8:
          MajorMinorVersion: 8.$(monitor8MinorVersion)
          ChannelQuality: $(monitor8Quality)
    steps:
    - pwsh: $(engPath)/Get-MonitorDropVersions.ps1 -Channel $(MajorMinorVersion)/$(ChannelQuality)
      displayName: Get Versions
    - powershell: |
        $customArgs = "$(MajorMinorVersion) --product-version monitor=$(monitorVer) --version-source-name dotnet/dotnet-monitor/$(MajorMinorVersion) --stable-branding=$(stableBranding)"
        
        $customArgsArray = @($customArgs)
        echo "##vso[task.setvariable variable=customArgsArray]$($customArgsArray | ConvertTo-Json -Compress -AsArray)"
      displayName: Set Custom Args
    - template: steps/update-dependencies.yml
      parameters:
        customArgsArray: $(customArgsArray)
