trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true
variables:
- template: ../common/templates/variables/dotnet/common.yml
stages:
- stage: DotNet
  condition: eq(variables['update-dotnet-enabled'], 'true')
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/installer)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - template: steps/update-dotnet-dependencies.yml
- stage: Monitor
  condition: eq(variables['update-monitor-enabled'], 'true')
  dependsOn: [] # Allows it to run in parallel
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/dotnet-monitor)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    strategy:
      matrix:
        Update6:
          MajorMinorVersion: 6.$(monitor6MinorVersion)
          ChannelQuality: $(monitor6Quality)
          StableBranding: $(monitor6StableBranding)
        Update7:
          MajorMinorVersion: 7.$(monitor7MinorVersion)
          ChannelQuality: $(monitor7Quality)
          StableBranding: $(monitor7StableBranding)
    steps:
    - pwsh: $(engPath)/Get-MonitorDropVersions.ps1 -Channel $(MajorMinorVersion)/$(ChannelQuality)
      displayName: Get Versions
    - template: steps/update-dependencies.yml
      parameters:
        customArgs: "$(MajorMinorVersion) --product-version monitor=$(monitorVer) --channel-name $(MajorMinorVersion)/$(ChannelQuality) --version-source-name dotnet/dotnet-monitor/$(MajorMinorVersion)"
        stableBranding: $(StableBranding)
