resources:
  pipelines:
  - pipeline: dotnet-monitor
    source: dotnet-dotnet-monitor
    trigger:
      branches:
        include:
        - main
        - feature/9.x
        - release/*
        - internal/release/*
      tags:
      - update-docker
      - real signed
trigger: none
pr: none

parameters:
  - name: dryRun
    displayName: Dry Run (Skip PR Creation)
    type: boolean
    default: false

variables:
- template: ../common/templates/variables/dotnet/common.yml
stages:
- stage: Monitor
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/dotnet-monitor)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - download: dotnet-monitor
      artifact: Build_Info
      displayName: "Download Build Info (Branch: $(resources.pipeline.dotnet-monitor.sourceBranch))"
    - pwsh: $(engPath)/Get-MonitorDropVersions.ps1 -BuildVersionFilePath "$(Pipeline.Workspace)/dotnet-monitor/Build_Info/dotnet-monitor.nupkg.buildversion"
      displayName: Get Versions
    - powershell: |
        Import-Module -force $(engPath)/DependencyManagement.psm1

        $scriptArgs = @{
          ProductVersion = "$(monitorMajorMinorVersion)"
          MonitorVersion = "$(monitorVer)"
          AzdoVariableName = 'updateDepsArgs'
          UseStableBranding = [bool]::Parse("$(stableBranding)")
          ReleaseState = $(Get-ProductReleaseState)
        }

        $(engPath)/Set-DotnetVersions.ps1 @scriptArgs
      displayName: Get update-dependencies args
    - powershell: |
        $customArgsArray = @("$(updateDepsArgs)")
        echo "##vso[task.setvariable variable=customArgsArray]$($customArgsArray | ConvertTo-Json -Compress -AsArray)"
      displayName: Set Custom Args
    - template: steps/update-dependencies-specific.yml
      parameters:
        customArgsArray: $(customArgsArray)
        dryRun: ${{ parameters.dryRun }}
