resources:
  pipelines:
  - pipeline: dotnet-monitor
    source: dotnet-dotnet-monitor
    trigger:
      branches:
        include:
        - main
        - release/*
        - internal/release/*
      tags:
      - update-docker
      - real signed
trigger: none
pr: none

variables:
- template: ../common/templates/variables/dotnet/common.yml
- group: DncEng-Partners-Tokens
- group: DotNet-AllOrgs-Darc-Pats

stages:
- stage: Monitor
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/dotnet-monitor)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - download: dotnet-monitor
      artifact: Build_Info
      displayName: "Download Build Info (Branch: $(resources.pipeline.dotnet-monitor.sourceBranch))"

    - pwsh: $(engPath)/Get-MonitorDropVersions.ps1 -BuildVersionFilePath "$(Pipeline.Workspace)/dotnet-monitor/Build_Info/dotnet-monitor.nupkg.buildversion"
      displayName: Get Versions

    - powershell: |
        $isInternalBuild = '$(resources.pipeline.dotnet-monitor.sourceBranch)'.StartsWith('refs/heads/internal/release/')
        echo "Is Internal Build: $isInternalBuild"
        echo "##vso[task.setvariable variable=IsInternalBuild]$($isInternalBuild.ToString().ToLowerInvariant())"
      displayName: Determine Build Type

    - template: steps/update-dependencies.yml
      parameters:
        versionInfosArray: "$(versionInfos)"
        useInternalBuild: $(IsInternalBuild)
