trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true
variables:
- template: variables/common.yml
jobs:
- job: UpdateDependencies
  pool: Hosted Ubuntu 1604
  steps:
  - script: $(engPath)/get-drop-versions.sh $(channel)
    displayName: Get Versions
  - script: docker build -t update-dependencies -f $(engPath)/update-dependencies/Dockerfile --pull .
    displayName: Build Update Dependencies Tool
  - script: >
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock update-dependencies
      --user $(dotnetDockerBot.userName)
      --email $(dotnetDockerBot.email)
      --password $(BotAccount-dotnet-docker-bot-PAT)
      --runtime-version $(runtimeVer)
      --sdk-version $(sdkVer)
      --aspnet-version $(aspnetVer)
      --compute-shas
    displayName: Run Update Dependencies
