trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true
variables:
- template: variables/common.yml
stages:
- stage: UpdateDependenciesDotNet
  condition: eq(variables['update-dotnet-enabled'], 'true')
  jobs:
  - job: UpdateDependenciesDotNet
    displayName: Update Dependencies (dotnet/installer)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - script: $(engPath)/get-drop-versions.sh $(channel)
      displayName: Get Versions
    - script: docker build -t update-dependencies -f $(engPath)/update-dependencies/Dockerfile --pull .
      displayName: Build Update Dependencies Tool
    - script: >
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock update-dependencies
        $(dockerfileVersion)
        --user $(dotnetDockerBot.userName)
        --email $(dotnetDockerBot.email)
        --password $(BotAccount-dotnet-docker-bot-PAT)
        --product-version runtime=$(runtimeVer)
        --product-version sdk=$(sdkVer)
        --product-version aspnet=$(aspnetVer)
        --version-source-name dotnet/core-sdk
        --compute-shas
      displayName: Run Update Dependencies
- stage: UpdateDependenciesDiagnostics
  condition: eq(variables['update-diagnostics-enabled'], 'true')
  dependsOn: [] # Allows it to run in parallel
  jobs:
  - job: UpdateDependenciesDiagnostics
    displayName: Update Dependencies (dotnet/diagnostics)
    variables:
      isEnabled: $(update-diagnostics-enabled)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - script: $(engPath)/get-drop-versions-monitor.sh $(monitorChannel)
      displayName: Get Versions
    - script: docker build -t update-dependencies -f $(engPath)/update-dependencies/Dockerfile --pull .
      displayName: Build Update Dependencies Tool
    - script: >
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock update-dependencies
        $(dockerfileVersion)
        --user $(dotnetDockerBot.userName)
        --email $(dotnetDockerBot.email)
        --password $(BotAccount-dotnet-docker-bot-PAT)
        --product-version monitor=$(monitorVer)
        --version-source-name dotnet/diagnostics
      displayName: Run Update Dependencies
