trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true

parameters:
  - name: skipPullRequest
    displayName: Skip Pull Request
    type: boolean
    default: false
  # This parameter will show up as a multi-select dropdown when queueing the pipeline
  - name: tools
    type: stringList
    displayName: Tools to update
    values:
      - "chisel"
      - "rocks-toolbox"
      - "syft"
      - "mingit"
    # Keep the default values in sync with allowed values so that the scheduled
    # pipeline runs always try to update all tools
    default:
      - "chisel"
      - "rocks-toolbox"
      - "syft"
      - "mingit"

variables:
- template: /eng/common/templates/variables/dotnet/common.yml@self
# Uses GitHub token to create pull requests
- template: /eng/common/templates/variables/dotnet/secrets.yml@self

extends:
  template: /eng/pipelines/pipelines/update-dependencies.yml@self
  parameters:
    channel: $(channel)
    tools: ${{ parameters.tools }}
    ${{ if ne(parameters.skipPullRequest, true) }}:
      gitHubAuthArgs: >-
        --user $(dotnetDockerBot.userName)
        --email $(dotnetDockerBot.email)
        --password $(BotAccount-dotnet-docker-bot-PAT)
