trigger: none
pr: none

variables:
- template: /eng/common/templates/variables/dotnet/common.yml@self
# This pipeline expects there to be a variable named "targetBranch" defined
# in the Azure Pipelines GUI. It should be able to be overridden at pipeline
# queue time. A pull request will be created targeting that branch.
# It is not a parameter since it needs to be permanent but also changed to the
# next release branch every month without modifying the pipeline YAML.

resources:
  pipelines:
  # All release pipelines are located at: https://dev.azure.com/dnceng/internal/_build?definitionScope=%5Cdotnet%5Crelease
  # Stage-DotNet-Prepare-Artifacts: https://dev.azure.com/dnceng/internal/_build?definitionId=1300
  # Stage-DotNet-Prepare-Artifacts-Test: https://dev.azure.com/dnceng/internal/_build?definitionId=1286
  - pipeline: "dotnet-staging-pipeline"
    source: "Stage-DotNet-Prepare-Artifacts"
    trigger: true

extends:
  template: /eng/pipelines/pipelines/update-dependencies-internal.yml@self
  parameters:
    buildId: "$(resources.pipeline.dotnet-staging-pipeline.runID)"
    stagingStorageAccount: "dotnetstage"
    targetBranch: "$(targetBranch)"
    gitServiceConnectionName: "$(updateDepsInt.serviceConnectionName)"
