trigger: none
pr: none

parameters:
  - name: skipPullRequest
    displayName: Skip Pull Request
    type: boolean
    default: false

variables:
- template: ../common/templates/variables/dotnet/common.yml
- group: DotNet-AllOrgs-Darc-Pats
stages:
- stage: DotNet
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/sdk)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - template: steps/update-dotnet-dependencies-specific.yml
      parameters:
        skipPullRequest: ${{ parameters.skipPullRequest }}
        useInternalBuild: true
        buildId: $(buildId)
