trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true

parameters:
  - name: skipPullRequest
    displayName: Skip Pull Request
    type: boolean
    default: false

variables:
- template: ../common/templates/variables/dotnet/common.yml

stages:
- stage: DotNet
  jobs:
  - job: UpdateDotNet
    displayName: Update .NET (dotnet/dotnet)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - template: steps/update-dotnet-dependencies.yml
      parameters:
        channel: $(channel)
        repo: "https://github.com/dotnet/dotnet"
        versionSourceName: "dotnet/dotnet"
        serviceConnection: "Darc: Maestro Production"
        skipPullRequest: ${{ parameters.skipPullRequest }}
  - template: jobs/update-tools.yml
    parameters:
      tools: ["chisel", "rocks-toolbox", "syft", "mingit"]
      skipPullRequest: ${{ parameters.skipPullRequest }}
