trigger: none
pr: none
schedules:
- cron: "0 13,17,22 * * Mon-Fri"
  displayName: M-F 3 times daily build
  branches:
    include:
    - nightly
variables:
- group: DotNet-Maestro
- template: variables/common.yml
jobs:
- job: UpdateDependencies
  pool: Hosted Ubuntu 1604
  steps:
  - script: $(engPath)/get-drop-versions.sh $(channel)
    displayName: Get Versions
  - script: docker build -t update-dependencies -f $(engPath)/update-dependencies/Dockerfile --pull .
    displayName: Build Update Dependencies Tool
  - script: >
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock update-dependencies
      --user dotnet-maestro-bot
      --email dotnet-maestro-bot@microsoft.com
      --password $(BotAccount-dotnet-maestro-bot-PAT)
      --runtime-version $(runtimeVer)
      --sdk-version $(sdkVer)
      --aspnet-version $(aspnetVer)
    displayName: Run Update Dependencies
