trigger: none
pr: none

parameters:
- name: buildId
  type: string
  default: ""

variables:
- template: /eng/common/templates/variables/dotnet/common.yml@self

extends:
  template: /eng/pipelines/pipelines/update-dependencies-internal.yml@self
  parameters:
    official: false
    buildId: ${{ parameters.buildId }}
    stagingStorageAccount: "dotnetstage"
    sourceBranch: "nightly"
    targetBranch: "unofficial/pipeline-$(Build.BuildId)"
    gitServiceConnectionName: "$(updateDepsInt-test.serviceConnectionName)"
    gitServiceConnectionClientId: "$(updateDepsInt-test.serviceConnection.clientId)"
