resources:
  pipelines:
  - pipeline: dotnet-monitor
    source: dotnet-dotnet-monitor
    trigger:
      branches:
        include:
        - main
        - feature/9.x
        - release/*
        - internal/release/*
      tags:
      - update-docker
      - real signed
trigger: none
pr: none

parameters:
  - name: skipPullRequest
    displayName: Skip Pull Request
    type: boolean
    default: false

variables:
- template: /eng/docker-tools/templates/variables/dotnet/common.yml@self
- template: /eng/docker-tools/templates/variables/dotnet/secrets.yml@self

stages:
- stage: Monitor
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/dotnet-monitor)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - checkout: self
      fetchDepth: 0
    - template: steps/install-dotnet.yml
    - pwsh: |
        $updateArgs = @(
          "monitor"
          "--pipeline-run-id"
          "$(resources.pipeline.dotnet-monitor.runID)"
        )

        if ("${{ parameters.skipPullRequest }}" -ne "true") {
          $updateArgs += @(
            "--user"
            "$(dotnetDockerBot.userName)"
            "--email"
            "$(dotnetDockerBot.email)"
            "--password"
            $env:DOTNET_DOCKER_BOT_PAT
          )
        }

        dotnet run --project "$(engPath)/update-dependencies/update-dependencies.csproj" -- @updateArgs
        exit $LASTEXITCODE
      displayName: Update .NET Monitor
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        ${{ if ne(parameters.skipPullRequest, true) }}:
          DOTNET_DOCKER_BOT_PAT: $(BotAccount-dotnet-docker-bot-PAT)
