trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true

variables:
- template: ../common/templates/variables/dotnet/common.yml

stages:
- stage: DotNet
  jobs:
  - job: UpdateDotNet
    displayName: Update .NET (dotnet/sdk)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - checkout: self
      fetchDepth: 1
    - template: steps/update-dotnet-dependencies.yml
      parameters:
        channel: "5708"
        repo: "https://github.com/dotnet/dotnet"
        versionSourceName: "dotnet/sdk"
        serviceConnection: "Darc: Maestro Production"
  # - template: jobs/update-tools.yml
  #   parameters:
  #     tools: ["chisel", "rocks-toolbox", "syft", "mingit"]
