trigger: none
pr: none

parameters:
- name: targetBranch
  type: string
  default: "nightly"
  displayName: Target branch for dependency update pull request.
# Comma-delimited list of stage container names (e.g., "stage-1234567,stage-2345678")
# Each stage container will be processed in sequence.
- name: stageContainers
  type: string
  default: ""
  displayName: Comma-delimited list of stage containers to process

variables:
- template: /eng/docker-tools/templates/variables/dotnet/common.yml@self

extends:
  template: /eng/pipelines/pipelines/update-dependencies-internal.yml@self
  parameters:
    stageContainers: "${{ parameters.stageContainers }}"
    stagingStorageAccount: "dotnetstage"
    targetBranch: "${{ parameters.targetBranch }}"
    gitServiceConnectionName: "$(updateDepsInt-test.serviceConnectionName)"
