trigger: none
pr: none

parameters:
- name: vmrChannel
  displayName: .NET VMR build channel (see aka.ms/bar)
  type: string
  default: ""
- name: aspireChannel
  displayName: Aspire build channel (see aka.ms/bar)
  type: string
  default: ""

variables:
- template: /eng/common/templates/variables/dotnet/common.yml@self
- group: DotNet-Docker-Common-2

extends:
  template: /eng/pipelines/pipelines/update-dependencies.yml@self
  parameters:
    vmrChannel: ${{ parameters.vmrChannel }}
    aspireChannel: ${{ parameters.aspireChannel }}
