trigger: none
pr: none
variables:
- template: variables/core.yml
jobs:
- job: UpdateReadmes
  pool: $(defaultLinuxAmd64PoolImage)
  steps:
  - template: ../common/templates/steps/init-docker-linux.yml
  - template: steps/set-public-source-branch-var.yml
  - template: ../common/templates/steps/set-image-info-path-var
    parameters:
      publicSourceBranch: $(publicSourceBranch)
  - template: steps/set-publish-mcrdocs-args-var.yml
  - template: ../common/templates/steps/publish-readmes.yml
  - template: ../common/templates/steps/cleanup-docker-linux.yml
