trigger: none
pr: none
variables:
- group: DotNet-Maestro
- template: variables/common.yml
jobs:
- job: UpdateDependencies
  pool: Hosted Ubuntu 1604
  steps:
  - script: docker build -t update-dependencies -f $(engPath)/update-dependencies/Dockerfile --pull .
    displayName: Build Update Dependencies Tool
  - script: >
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock update-dependencies
      --user dotnet-maestro-bot
      --email dotnet-maestro-bot@microsoft.com
      --password $(BotAccount-dotnet-maestro-bot-PAT)
      --build-info $(buildInfoUrl)
    displayName: Run Update Dependencies
