trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true
variables:
- template: ../common/templates/variables/dotnet/common.yml
stages:
- stage: DotNet
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/installer)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - template: steps/update-dotnet-dependencies.yml
