trigger: none
pr: none
variables:
- template: variables/common.yml
jobs:
- job: VersionMonitor
  pool: Hosted Ubuntu 1604
  workspace:
    clean: all
  steps:
  - template: ../common/templates/steps/init-docker-linux.yml
  - script: >
      $(runImageBuilderCmd) updateVersions
      $(dotnetBot-userName)
      $(dotnetBot-email)
      $(dotnet-bot-user-repo-adminrepohook-pat)
      --git-branch master
      --git-owner dotnet
      --architecture '*'
    displayName: Update Docker Image Version Info
  - template: ../common/templates/steps/cleanup-docker-linux.yml
