parameters:
  buildMatrixType: platformDependencyGraph
  testMatrixType: platformVersionedOs
  customBuildLegGrouping: ""
  customBuildInitSteps: []
  
  linuxAmdBuildJobTimeout: 60
  linuxArmBuildJobTimeout: 60
  windowsAmdBuildJobTimeout: 60
  windowsArmBuildJobTimeout: 60

  linuxAmdTestJobTimeout: 60
  linuxArmTestJobTimeout: 60
  windowsAmdTestJobTimeout: 60
  windowsArmTestJobTimeout: 60

stages:

################################################################################
# Build Images
################################################################################
- stage: Build
  condition: and(succeeded(), contains(variables['stages'], 'build'))
  jobs:
  - template: ../jobs/generate-matrix.yml
    parameters:
      matrixType: ${{ parameters.buildMatrixType }}
      name: GenerateBuildMatrix
      customBuildLegGrouping: ${{ parameters.customBuildLegGrouping }}

  - template: ../jobs/build-images.yml
    parameters:
      name: Build_Linux_amd64
      pool: # linuxAmd64Pool
        name: DotNetCore-Linux
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.LinuxAmd64']
      dockerClientOS: linux
      buildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_Linux_arm64v8
      pool: # linuxArm64v8Pool
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands:
        - agent.os -equals linux
        - RemoteDockerServerOS -equals linux
        - RemoteDockerServerArch -equals aarch64
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.LinuxArm64v8']
      useRemoteDockerServer: true
      dockerClientOS: linux
      buildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_Linux_arm32v7
      pool: # linuxArm32v7Pool
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands:
        - agent.os -equals linux
        - RemoteDockerServerOS -equals linux
        - RemoteDockerServerArch -equals aarch64
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.LinuxArm32v7']
      useRemoteDockerServer: true
      dockerClientOS: linux
      buildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_Windows1809_amd64
      pool: # windows1809Amd64
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands: VSTS_OS -equals Windows_Server_2019_Data_Center_RS5
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.Windows1809Amd64']
      dockerClientOS: windows
      buildJobTimeout: ${{ parameters.windowsAmdBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_Windows1809_arm32
      pool: # Windows1809Arm32Pool
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands:
        - agent.os -equals linux
        - RemoteDockerServerOS -equals nanoserver-1809
        - RemoteDockerServerArch -equals arm32
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.Windows1809Arm32']
      dockerClientOS: linux
      useRemoteDockerServer: true
      buildJobTimeout: ${{ parameters.windowsArmBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_Windows1903_amd64
      pool: # windows1903Amd64
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands: VSTS_OS -equals Windows_Server_2019_Data_Center_1903
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.Windows1903Amd64']
      dockerClientOS: windows
      buildJobTimeout: ${{ parameters.windowsAmdBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_Windows1909_amd64
      pool: # windows1909Amd64
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands: VSTS_OS -equals Windows-ServerDatacenter-1909
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.Windows1909Amd64']
      dockerClientOS: windows
      buildJobTimeout: ${{ parameters.windowsAmdBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}
  - template: ../jobs/build-images.yml
    parameters:
      name: Build_WindowsLtsc2016_amd64
      pool: # windows1607Amd64Pool
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          name: DotNetCore-Docker
        demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.WindowsLtsc2016Amd64']
      dockerClientOS: windows
      buildJobTimeout: ${{ parameters.windowsAmdBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}

- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  ################################################################################
  # Post-Build
  ################################################################################
  - stage: Post_Build
    dependsOn: Build
    condition: and(succeeded(), contains(variables['stages'], 'build'))
    jobs:
    - template: ../jobs/post-build.yml

  ################################################################################
  # Test Images
  ################################################################################
  - stage: Test
    dependsOn: Post_Build
    condition: "
      and(
        contains(variables['stages'], 'test'),
        or(
          and(
            succeeded(),
            contains(variables['stages'], 'build')),
          not(contains(variables['stages'], 'build'))))"
    jobs:
    - template: ../jobs/generate-matrix.yml
      parameters:
        matrixType: ${{ parameters.testMatrixType }}
        name: GenerateTestMatrix

    - template: ../jobs/test-images-linux-client.yml
      parameters:
        name: Test_Linux_amd64
        pool: # linuxAmd64Pool
          name: DotNetCore-Linux
        matrix: dependencies.GenerateTestMatrix.outputs['matrix.LinuxAmd64']
        testJobTimeout: ${{ parameters.linuxAmdTestJobTimeout }}
    - template: ../jobs/test-images-linux-client.yml
      parameters:
        name: Test_Linux_arm64v8
        pool: # linuxArm64v8Pool
          name: DotNetCore-Docker
          demands:
          - agent.os -equals linux
          - RemoteDockerServerOS -equals linux
          - RemoteDockerServerArch -equals aarch64
        matrix: dependencies.GenerateTestMatrix.outputs['matrix.LinuxArm64v8']
        testJobTimeout: ${{ parameters.linuxArmTestJobTimeout }}
        useRemoteDockerServer: true
    - template: ../jobs/test-images-linux-client.yml
      parameters:
        name: Test_Linux_arm32v7
        pool: # linuxArm32v7Pool
          name: DotNetCore-Docker
          demands:
          - agent.os -equals linux
          - RemoteDockerServerOS -equals linux
          - RemoteDockerServerArch -equals aarch64
        matrix: dependencies.GenerateTestMatrix.outputs['matrix.LinuxArm32v7']
        testJobTimeout: ${{ parameters.linuxArmTestJobTimeout }}
        useRemoteDockerServer: true
    - template: ../jobs/test-images-windows-client.yml
      parameters:
        name: Test_Windows1809_amd64
        pool: # windows1809Amd64
          name: DotNetCore-Docker
          demands: VSTS_OS -equals Windows_Server_2019_Data_Center_RS5
        matrix: dependencies.GenerateTestMatrix.outputs['matrix.Windows1809Amd64']
        testJobTimeout: ${{ parameters.windowsAmdTestJobTimeout }}
    - template: ../jobs/test-images-linux-client.yml
      parameters:
        name: Test_Windows1809_arm32
        pool: # Windows1809Arm32Pool
          name: DotNetCore-Docker
          demands:
          - agent.os -equals linux
          - RemoteDockerServerOS -equals nanoserver-1809
          - RemoteDockerServerArch -equals arm32
        matrix: dependencies.GenerateTestMatrix.outputs['matrix.Windows1809Arm32']
        testJobTimeout: ${{ parameters.windowsArmTestJobTimeout }}
        useRemoteDockerServer: true
    - template: ../jobs/test-images-windows-client.yml
      parameters:
        name: Test_Windows1903_amd64
        buildDependencies: Build_Windows1903_amd64
        pool: # windows1903Amd64
          name: DotNetCore-Docker
          demands: VSTS_OS -equals Windows_Server_2019_Data_Center_1903
        matrix: dependencies.GenerateTestMatrix.outputs['matrix.Windows1903Amd64']
        testJobTimeout: ${{ parameters.windowsAmdTestJobTimeout }}
    - template: ../jobs/test-images-windows-client.yml
      parameters:
        name: Test_Windows1909_amd64
        buildDependencies: Build_Windows1909_amd64
        pool: # windows1909Amd64
          name: DotNetCore-Docker
          demands: VSTS_OS -equals Windows-ServerDatacenter-1909
        matrix: dependencies.GenerateTestMatrix.outputs['matrix.Windows1909Amd64']
        testJobTimeout: ${{ parameters.windowsAmdTestJobTimeout }}
    - template: ../jobs/test-images-windows-client.yml
      parameters:
        name: Test_WindowsLtsc2016_amd64
        buildDependencies: Build_WindowsLtsc2016_amd64
        pool: # windows1607Amd64Pool
          name: DotNetCore-Docker
          demands: VSTS_OS -equals Windows_Server_2016_Data_Center_with_Containers
        matrix: dependencies.GenerateTestMatrix.outputs['matrix.WindowsLtsc2016Amd64']
        testJobTimeout: ${{ parameters.windowsAmdTestJobTimeout }}

  ################################################################################
  # Publish Images
  ################################################################################
  - stage: Publish
    dependsOn: Test
    condition: "
      and(
        contains(variables['stages'], 'publish'),
        or(
          or(
            and(
              and(
                contains(variables['stages'], 'build'),
                succeeded('Post_Build')),
              and(
                contains(variables['stages'], 'test'),
                succeeded('Test'))),
            or(
              and(
                not(contains(variables['stages'], 'build')),
                and(
                  contains(variables['stages'], 'test'),
                  succeeded('Test'))),
              and(
                not(contains(variables['stages'], 'test')),
                and(
                  contains(variables['stages'], 'build'),
                  succeeded('Post_Build'))))),
          not(
            or(
              contains(variables['stages'], 'build'),
              contains(variables['stages'], 'test')))))"
    jobs:
    - template: ../jobs/publish.yml
      parameters:
        pool: # linuxAmd64Pool
          name: DotNetCore-Linux
