ARG sdk_image
ARG runtime_image

FROM $sdk_image as build

ARG rid
ARG NuGetFeedPassword
ARG port

EXPOSE $port

WORKDIR /source
COPY NuGet.config .
WORKDIR /source/app
COPY app/*.csproj .
RUN dotnet restore -r %rid%

COPY app/ .
RUN dotnet build --no-restore


FROM build AS test

ARG rid
ARG NuGetFeedPassword

WORKDIR /source/tests

COPY tests/*.csproj .
RUN dotnet restore -r %rid%

COPY tests/ .
ENTRYPOINT ["dotnet", "test", "--logger:trx", "--no-restore"]


FROM build as publish_fx_dependent
RUN dotnet publish --no-restore -c Release -o out


FROM $runtime_image AS fx_dependent_app

ARG port

EXPOSE $port
WORKDIR /app
COPY --from=publish_fx_dependent /source/app/out ./
ENTRYPOINT ["dotnet", "app.dll"]
