ARG REPO=mcr.microsoft.com/dotnet/runtime
FROM $REPO:{{VARIABLES["dotnet|5.0|product-version"]}}-{{OS_VERSION}}{{ARCH_TAG_SUFFIX}}

# .NET globalization APIs will use invariant mode by default because DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true is set
# by the base runtime-deps image. See https://aka.ms/dotnet-globalization-alpine-containers for more information.

ENV ASPNET_VERSION={{VARIABLES["aspnet|5.0|build-version"]}}

{{InsertTemplate("../Dockerfile.linux.install-aspnet")}}
