ARG REPO=mcr.microsoft.com/dotnet/runtime
FROM $REPO:{{VARIABLES["dotnet|5.0|product-version"]}}-{{OS_VERSION}}{{ARCH_TAG_SUFFIX}}

ENV ASPNET_VERSION={{VARIABLES["aspnet|5.0|build-version"]}}

{{InsertTemplate("../Dockerfile.linux.install-aspnet")}}
