apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-non-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: dotnetnonroot.azurecr.io/aspnetapp
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-non-root
spec:
  type: NodePort
  selector:
    app: aspnetapp
  ports:
    - port: 8080
