parameters:
  tools: []

jobs:
- ${{ each tool in parameters.tools }}:
  - job: UpdateDependencies_${{ replace(tool, '-', '_') }}
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - template: update-dependencies.yml
      parameters:
        customArgsArray: >
          ["
          9.0
          --tool ${{ tool }}
          --version-source-name=${{ tool }}
          --source-branch=nightly
          --org dnceng
          --project $(System.TeamProject)
          --repo $(Build.Repository.Name)
          --target-branch $(Get-Branch)
          "]
