parameters:
  tools: []

jobs:
- ${{ each tool in parameters.tools }}:
  - job: UpdateDependencies_${{ replace(tool, '-', '_') }}
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - powershell: echo "Updating ${{ tool }}"
