parameters:
  tools: []

jobs:
- ${{ each tool in parameters.tools }}:
  - job: UpdateDependencies_${{ replace(tool, '-', '_') }}
    displayName: Update ${{ tool }}
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - powershell: |
        Import-Module -force $(engPath)/DependencyManagement.psm1

        $args=("9.0" + `
            " --tool ${{ tool }}" + `
            " --version-source-name ${{ tool }}" + `
            " --source-branch nightly" + `
            " --org dnceng" + `
            " --project $(System.TeamProject)" + `
            " --repo $(Build.Repository.Name)" + `
            " --target-branch $(Get-Branch)")

        echo "##vso[task.setvariable variable=customArgsArray]$($args | ConvertTo-Json -Compress -AsArray)"
      displayName: Set up args
    - template: /eng/pipelines/steps/update-dependencies.yml
      parameters:
        customArgsArray: "$(customArgsArray)"
