parameters:
  tools: []
  dryRun: false

jobs:
- ${{ each tool in parameters.tools }}:
  - job: UpdateDependencies_${{ replace(tool, '-', '_') }}
    displayName: Update ${{ tool }}
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - template: /eng/pipelines/steps/update-dependencies.yml
      parameters:
        dryRun: ${{ parameters.dryRun }}
        args: >
          specific 9.0
          --tool ${{ tool }}
          --version-source-name ${{ tool }}
          --source-branch nightly
          --target-branch nightly
          --org dnceng
          --project $(System.TeamProject)
          --repo $(Build.Repository.Name)
