# A wrapper template around the common build-test-publish-repo template with settings
# specific to the .NET team's infrastructure.

parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null
  buildMatrixCustomBuildLegGroupArgs: ""
  customBuildInitSteps: []
  customPublishInitSteps: []
  windowsAmdBuildJobTimeout: 60
  windowsAmdTestJobTimeout: 60
  linuxAmdBuildJobTimeout: 60
  linuxAmd64Pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  buildMatrixType: platformDependencyGraph
  testMatrixType: platformVersionedOs

stages:
- template: ../build-test-publish-repo.yml
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    buildMatrixCustomBuildLegGroupArgs: ${{ parameters.buildMatrixCustomBuildLegGroupArgs }}
    customBuildInitSteps: ${{ parameters.customBuildInitSteps }}
    customPublishInitSteps: ${{ parameters.customPublishInitSteps }}
    windowsAmdBuildJobTimeout: ${{ parameters.windowsAmdBuildJobTimeout }}
    windowsAmdTestJobTimeout: ${{ parameters.windowsAmdTestJobTimeout }}
    linuxAmdBuildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
    buildMatrixType: ${{ parameters.buildMatrixType }}
    testMatrixType: ${{ parameters.testMatrixType }}

    internalVersionsRepoRef: InternalVersionsRepo
    publicVersionsRepoRef: PublicVersionsRepo
    
    ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
      customPublishVariables:
      - group: DotNet-AllOrgs-Darc-Pats

    linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}
    linuxArm64Pool:
        ${{ if eq(variables['System.TeamProject'], parameters.publicProjectName) }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
          name: DotNetCore-Docker
        demands:
        - Agent.OS -equals linux
        - Agent.OSArchitecture -equals ARM64
    linuxArm32Pool:
        ${{ if eq(variables['System.TeamProject'], parameters.publicProjectName) }}:
          name: DotNetCore-Docker-Public
        ${{ if eq(variables['System.TeamProject'], parameters.internalProjectName) }}:
          name: DotNetCore-Docker
        demands:
        - Agent.OS -equals linux
        - Agent.OSArchitecture -equals ARM64
    windows2016Pool: Docker-2016-${{ variables['System.TeamProject'] }}
    windows1809Pool: Docker-1809-${{ variables['System.TeamProject'] }}
    windows2004Pool: Docker-2004-${{ variables['System.TeamProject'] }}
    windows20H2Pool: Docker-20H2-${{ variables['System.TeamProject'] }}
    windows2022Pool: Docker-2022-${{ variables['System.TeamProject'] }}
