ARG SYFT_IMAGE_NAME
ARG TARGET_IMAGE_NAME

FROM ${SYFT_IMAGE_NAME} AS syft
FROM ${TARGET_IMAGE_NAME} AS scan-image

FROM syft AS run-scan
ARG TARGET_IMAGE_NAME
ENV SYFT_CHECK_FOR_APP_UPDATE=0 \
    SYFT_SOURCE_NAME=${TARGET_IMAGE_NAME}
USER root
RUN --mount=from=scan-image,source=/,target=/rootfs \
    ["/syft", "scan", "/rootfs/", "--select-catalogers", "image", "--output", "spdx-json=/manifest.spdx.json"]

FROM scratch AS output
COPY --from=run-scan /manifest.spdx.json /manifest.spdx.json
