<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Microsoft.DotNet.Docker.UpdateDependencies</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UpdateDependencies.Tests" />
    <!-- Allows Moq to create mocks of internal types -->
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../shared/Microsoft.DotNet.Docker.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.14.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
    <PackageReference Include="LibGit2Sharp" Version="0.30.0" />
    <PackageReference Include="Microsoft.DotNet.DarcLib" Version="1.1.0-beta.25461.2" />
    <PackageReference Include="Microsoft.DotNet.GitAutomation" Version="0.3.0-beta.26453.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.TeamFoundationServer.Client" Version="19.232.0-preview" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.2" />
  </ItemGroup>
</Project>
