trigger:
  batch: true
  branches:
    include:
    - nightly
pr: none

variables:
- template: ../variables/common-official.yml
- name: manifest
  value: manifest.json
jobs:
- template: ../jobs/build-test-publish-repo.yml
