trigger:
  batch: true
  branches:
    include:
    - nightly
pr: none
variables:
- group: DotNet-Docker-Common
- group: DotNet-Docker-Secrets
- name: manifest
  value: manifest.json
jobs:
- template: ../jobs/build-test-publish-repo.yml
