trigger: none
pr: none
variables:
- group: DotNet-Maestro

jobs:
- job: UpdateDependencies
  pool: Hosted Ubuntu 1604
  steps:
  - script: |
      cwd=$(pwd)
      curl -SLo sdk.zip https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/$(channel)/dotnet-sdk-latest-win-x64.zip
      unzip sdk.zip -d $cwd/sdk

      cd $cwd/sdk/sdk
      sdkVersionsPath=$(find . -name .version)
      sdkVer=$(cat $sdkVersionsPath | head -2 | tail -1)
      
      cd $cwd/sdk/shared/Microsoft.NETCore.App
      runtimeVersionsPath=$(find . -name .version)
      runtimeVer=$(cat $runtimeVersionsPath | tail -1)

      cd $cwd/sdk/shared/Microsoft.AspNetCore.App
      aspnetVersionsPath=$(find . -name .version)
      aspnetVer=$(cat $aspnetVersionsPath | tail -1)

      echo "##vso[task.setvariable variable=sdkVer]$sdkVer"
      echo "##vso[task.setvariable variable=runtimeVer]$runtimeVer"
      echo "##vso[task.setvariable variable=aspnetVer]$aspnetVer"
    displayName: Get Versions
  - script: docker build -t update-dependencies -f ./scripts/update-dependencies/Dockerfile --pull .
    displayName: Build Update Dependencies Tool
  - script: >
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock update-dependencies
      --user dotnet-maestro-bot
      --email dotnet-maestro-bot@microsoft.com
      --password $(BotAccount-dotnet-maestro-bot-PAT)
      --runtime-version $(runtimeVer)
      --sdk-version $(sdkVer)
      --aspnet-version $(aspnetVer)
    displayName: Run Update Dependencies
  - script: docker system prune -a -f --volumes
    displayName: Cleanup Docker
