name: Backport PR to branch
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  backport:
    uses: lbussell/arcade/.github/workflows/backport-base.yml@workflow-conflict-resolution
    with:
      repository_owners: lbussell
      pr_description_template: |
        Backport of #%source_pr_number% to %target_branch%

        /cc %cc_users%
      conflict_resolution_command: pwsh ./eng/dockerfile-templates/Get-GeneratedDockerfiles.ps1 && pwsh ./eng/readme-templates/Get-GeneratedReadmes.ps1
